<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>data – zealhmm</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e8ceec9fd8916a5f8990aca9c03c0672.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/sawers-rellan-labs/zealhmm"> 
<span class="menu-text">zealhmm</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./DATA.html" aria-current="page"> 
<span class="menu-text">Data provenance</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><h1 class="title display-7"></h1></header><div class="quarto-title-block"><div class="quarto-title-tools-only"><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>




<section id="data-provenance" class="level1">
<h1>Data provenance</h1>
<p><code>data/</code>, <code>results/</code>, and <code>sim/</code> are <strong>gitignored</strong> (bulk inputs / generated outputs — not tracked). Large inputs live on the mount and are referenced here; resolve the mount roots with <code>R/staging.R::bzea_mounts()</code> (<code>pick()</code> fallback). This file is the tracked record of where everything comes from.</p>
<section id="mount-roots" class="level2">
<h2 class="anchored" data-anchor-id="mount-roots">Mount roots</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 67%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Alias</th>
<th>Resolved by <code>bzea_mounts()</code></th>
<th>Holds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>CAS</code> (cassini)</td>
<td><code>/Volumes/rsstu/.../tlaloc/cassini</code> → <code>/Volumes/tlaloc/cassini</code> → <code>/Volumes/cassini</code></td>
<td>pangene counts, gene→pangene map, B73 gene coords (ATLAS)</td>
</tr>
<tr class="even">
<td><code>MNT</code> (ancestry)</td>
<td><code>/Volumes/rsstu/.../BZea/bzeaseq/ancestry</code> → <code>/Volumes/BZea/bzeaseq/ancestry</code></td>
<td>per-bin <code>ALT_FREQ</code> <code>*_bin_genotypes.tsv</code> (dense skim, binhmm)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-sources-naming-source-caller" class="level2">
<h2 class="anchored" data-anchor-id="data-sources-naming-source-caller">Data sources (naming <code>&lt;Source&gt;-&lt;Caller&gt;</code>)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 27%">
<col style="width: 32%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Modality</th>
<th>Marker set</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Skim</td>
<td>low-cov WGS (~0.4×)</td>
<td>50K panel (thinned) + dense ~27.6 M wideseq</td>
<td>TP teosinte–B73 wideseq filter; MAF ≥ 0.05</td>
</tr>
<tr class="even">
<td>BrB</td>
<td>3′ RNA-seq (BRB-seq)</td>
<td>wideseq-thinned counts + cassini pangene</td>
<td>expression-driven depth; ASE</td>
</tr>
<tr class="odd">
<td>Target-seq</td>
<td>MolBreeding 45K, high cov</td>
<td>45K array</td>
<td>completeness / Holland-style cross-check only</td>
</tr>
</tbody>
</table>
<p>The ~27.6 M wideseq set = Schnable et al.&nbsp;2023 teosinte/<em>Tripsacum</em> VCF → biallelic → MAF ≥ 0.05 (<code>wideseq_ref</code>); GATK <code>CollectAllelicCounts</code> tallies skim/BRB reads at those positions. (memory <code>snp50k-cohort-provenance</code>, <code>gatk-table-readcount-standard</code>.)</p>
</section>
<section id="staged-subset-skim-sweep-data-gitignored-33-mb" class="level2">
<h2 class="anchored" data-anchor-id="staged-subset-skim-sweep-data-gitignored-33-mb">Staged subset: skim sweep (<code>data/</code>, gitignored, ~33 MB)</h2>
<p><code>stage_sanity_check_paint.R</code> copies the 11-sample vary-skim cohort (B73 control + 10 NILs) into <code>data/</code>, organized by <strong>(source × input type)</strong> and consumed by <code>analysis/nilhmm_sanity_check_paint.qmd</code>. Verified: the note reproduces the original zealtiger output <strong>row-for-row</strong> (1709 segments, all 6 tracks identical).</p>
<pre><code>data/
  ref/                                genome-level, dataset-independent
    gene_to_pangene.tsv               ATLAS: pangene &lt;-&gt; B73 gene map
    b73_gene_coords.tsv               ATLAS: B73 gene coordinates
  skimsweep/                          the vary-skim cohort
    coverage_sweep_members.csv        full sweep table (note filters to vary_skim)
    skim/counts_50k/&lt;skim&gt;.tsv        -&gt; Skim-nNIL, Skim-rtiger
    skim/bins/&lt;skim&gt;_bin_genotypes.tsv-&gt; Skim-binhmm  (PER-SAMPLE only, never the aggregate)
    brb/counts_wideseq/&lt;brb&gt;.tsv      -&gt; BrB-nNIL, BrB-rtiger
    brb/pangene/&lt;species&gt;/&lt;brb&gt;.pangene_counts.tsv  -&gt; BrB-atlas</code></pre>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Staged path</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>skimsweep/coverage_sweep_members.csv</code>, <code>skim/counts_50k/</code>, <code>brb/counts_wideseq/</code></td>
<td>zealtiger repo</td>
</tr>
<tr class="even">
<td><code>skim/bins/&lt;skim&gt;_bin_genotypes.tsv</code></td>
<td>rsstu <code>BZea/bzeaseq/ancestry/&lt;skim&gt;_bin_genotypes.tsv</code> (per-sample)</td>
</tr>
<tr class="odd">
<td><code>brb/pangene/</code>, <code>ref/</code></td>
<td>rsstu <code>tlaloc/cassini/</code> (<code>results/&lt;species&gt;/pangene/</code>, <code>data/pangene/</code>, <code>data/meta/</code>)</td>
</tr>
</tbody>
</table>
<p>Re-stage with <code>Rscript stage_sanity_check_paint.R</code> <strong>run with the sandbox disabled</strong> — both shares live under the <code>rsstu</code> automount, which the default sandbox cannot see (it reports the files as missing).</p>
</section>
<section id="teonam-genotypes-datateonam-gitignored-236-mb" class="level2">
<h2 class="anchored" data-anchor-id="teonam-genotypes-datateonam-gitignored-236-mb">TeoNAM genotypes (<code>data/teonam/</code>, gitignored, ~236 MB)</h2>
<p>Recoded TeoNAM SNP genotypes (Chen et al.&nbsp;2019, <em>Genetics</em> 213:1065; <code>chen2019teonam</code>). The genotypes cited in the paper at CyVerse <code>/iplant/home/shared/panzea/genotypes/GBS/TeosinteNAM</code> are <strong>no longer reachable</strong> — the whole <code>panzea</code> collection returns “not found” for our account and for anonymous CyVerse access (panzea.org still routes there and requires a CyVerse login, so it is likely permission-gated to a group we’re not in, not necessarily deleted). Figshare (9820178 / 9250682) has phenotypes/supplement only; panzea.org’s Cornell archive has only the older BC2S3 population (Yang et al.&nbsp;2019 PNAS, <code>yang2019genetic</code>).</p>
<p><strong>Source used instead:</strong> the EasiGP repo (Tomura et al.&nbsp;2025, bioRxiv <code>10.1101/2025.07.15.664852</code>, <code>tomura2025ensemble</code>) vendors a recoded copy.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td>Paper</td>
<td>Tomura et al.&nbsp;2025, bioRxiv <code>10.1101/2025.07.15.664852</code> (<code>tomura2025ensemble</code>)</td>
</tr>
<tr class="even">
<td>Repo</td>
<td>https://github.com/ShunichiroT/EasiGP</td>
</tr>
<tr class="odd">
<td>Commit</td>
<td><code>259c242006bce415a8995be1833ef44399655718</code> (2026-06-16)</td>
</tr>
<tr class="even">
<td>Path in repo</td>
<td><code>Data/TeoNAM/</code></td>
</tr>
<tr class="odd">
<td><code>TeoNAM_genotype.zip</code> sha256</td>
<td><code>3a8b5adcdff6ed162032347ecaabe25fed5384ea8ed387f0b22fe492b2c6f918</code></td>
</tr>
</tbody>
</table>
<p>Staged files (copied verbatim; <code>TeoNAM_genotype.csv</code> is the unzipped <code>TeoNAM_genotype.zip</code>):</p>
<pre><code>data/teonam/
  TeoNAM_genotype.csv        2,434 lines x ~51,483 markers; 0/1/2 coding
                             (0 = W22 hom, 1 = het, 2 = teosinte hom — paper's coding)
  TeoNAM_phenotype.csv       2,434 lines; traits DTA, ASI only (2 of the paper's 22)
  markers_v2.csv            51,544 markers; chromosome,name,start,end
                             names like S1_10045 = chr1 / AGPv2 position 10045 (start/end are 0)
  chrom.csv                  per-family chromosome spans
  gene_info.csv              flowering-gene markers (Dong 2012, Wisser 2019)
  W22TIL{01,03,11,14,25}_genotype.csv / _phenotype.csv   the 5 teosinte-parent subpopulations
  W22TIL01_subset_*          small subset used by EasiGP as a quick example
  TeoNAM_genotype.zip        original artifact (kept for integrity)</code></pre>
<p><strong>Caveats (verify before analysis):</strong> - Numeric <strong>dosage matrix only</strong> — no raw HapMap / ref-alt alleles. Fine for ancestry-HMM (0/1/2 <em>is</em> the W22↔︎teosinte ancestry dosage); insufficient if raw allele calls or an AGPv2 VCF are needed (positions survive only in the marker names). - <strong>Line count 2,434 exceeds the paper’s 1,257 RILs — resolved (2026-07-04):</strong> the file is EasiGP’s per-family files concatenated, and each family file already doubles every line. The two copies of a line differ <strong>only in <code>2</code> vs <code>2.0</code> integer/decimal formatting</strong> — numerically identical (0/1,197 disagree). Cleaned to <code>TeoNAM_genotype_clean.csv</code> (see characterization below): dedup → <strong>1,237</strong> unique lines, all cells decimal. - “Adjusted example data” per EasiGP’s <code>Data/README</code> — treat as a re-derived convenience copy, not the authoritative release. For the authoritative genotypes, request access to the CyVerse <code>panzea</code> collection from the authors (Qiuyue Chen / John Doebley). - <strong>Assembly = AGPv2, documented first-party by Qiuyue Chen (not by EasiGP).</strong> The marker-name positions (<code>S[chr]_[pos]</code>) are B73 AGPv2, confirmed by three sources:</p>
<ol type="1">
<li><p><strong>Chen’s own genotype-release README</strong> (<code>data/teonam/9250682/Genotype_files_ReadMe.docx</code>, shared directly by Qiuyue Chen from her Google Drive) — the authoritative, first-party statement: &gt; “The genetic map was estimated separately for each subpopulation using est.map function &gt; in R/qtl, and the physical position is represented in marker name with **B73 V2 position &gt; (S[chr]_[pos])**.”</p></li>
<li><p><strong>Chen et al.&nbsp;2019</strong> (Genetics 213:1065): &gt; “The genotypic data were uploaded with <strong>AGPv2 position in the marker name</strong>.” (Data Availability) &gt; “The <strong>B73 reference genome v2</strong> was used to determine marker order…” (Methods)</p>
<p>AGPv4 appears in Chen 2019 <strong>only</strong> for <em>reporting</em> QTL positions (CrossMap-lifted from AGPv2); the genotype marker-name coordinates are AGPv2.</p></li>
<li><p><strong>EasiGP is silent on assembly.</strong> The EasiGP repo and paper (Tomura et al.&nbsp;2025, <em>Plant Genome</em>, doi:10.1002/tpg2.70138) only cite “adjusted example data from the TeoNAM dataset (Chen et al., 2019)” and never mention a genome build — so the version documentation is entirely Chen’s.</p></li>
</ol>
<p><strong>Marker-name identity checks (2026-07-07)</strong> tying EasiGP back to Chen’s documented panel: - Chen’s <code>TeoNAM.composite.genetic.map.51544snp.txt</code> (51,544 names) <strong>== EasiGP <code>marker_info.csv</code> (51,544 names)</strong>: identical name sets, 0 unique to either side. - EasiGP <code>marker_info.csv</code> is byte-identical to our <code>markers_v2.csv</code> (md5 <code>6b29c715…</code>). - Our analyzed genotype matrix <code>TeoNAM_genotype_clean.csv</code> (51,482 columns) is a clean subset of Chen’s names (0 unrecognized columns; 62 Chen markers absent = the known 51,544→51,482 drop). - Independent physical check: per-chromosome max marker position fills the AGPv2 length and falls ~6–7 Mb short of v4/v5 (e.g.&nbsp;chr1 max 301,252,447 &lt; AGPv2 301,354,135 « v4 307,041,717).</p>
<p>(EasiGP repo clone kept at <code>agent/EasiGP/</code>. Chen’s Drive release, incl.&nbsp;the README, composite map, phenotypes, and — per the README — the 118,838-SNP GWAS HapMap + raw <code>.h5</code>, is under <code>data/teonam/9250682/</code>.)</p>
<p><strong>Genotype-matrix characterization (measured 2026-07-04, full-scan of the raw and cleaned files).</strong> Raw <code>TeoNAM_genotype.csv</code>: 2,434 rows × 51,482 marker columns (cols 4–51485; first 3 = <code>ID, population, factor</code>), CRLF endings. Cleaned artifact <code>TeoNAM_genotype_clean.csv</code>: <strong>1,237 rows × 51,482 markers, all decimals, LF</strong> (dedup + <code>2</code>→<code>2.0</code> normalization; original preserved).</p>
<ul>
<li><p><strong>The 2,434→1,237 doubling is a formatting artifact, not replicates.</strong> Each line appears twice (byte-identical ID); the two copies are numerically identical and differ only in integer vs decimal spelling (<code>2</code> vs <code>2.0</code>). Raw matrix had 328,590 integer-formatted cells (0.26%) vs 33.4M decimal; the clean file has <strong>0</strong> integer cells. Dedup keeps one copy → 1,237 unique lines.</p></li>
<li><p><strong>Imputed / complete within family — proven, not inferred.</strong> For every family, each marker column is present in either <em>all</em> of the family’s lines or <em>none</em> (0 partially-present columns) → within-family missingness <strong>0%</strong>; hard <code>0/1/2</code> calls only. This is the paper’s per-subpopulation FSFHap-imputed output — not raw GBS, and not the cross-imputed/thinned 4,578-marker JLM matrix.</p></li>
<li><p><strong>Block-sparse union (73% blank, 100% structural):</strong> each line is blank at other families’ markers. Per-family line/marker counts (cleaned, one row per line):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Family</th>
<th>nLines (clean)</th>
<th>markers (present per line)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>W22TIL01</td>
<td>220</td>
<td>13,042</td>
</tr>
<tr class="even">
<td>W22TIL03</td>
<td>267</td>
<td>16,076</td>
</tr>
<tr class="odd">
<td>W22TIL11</td>
<td>218</td>
<td>13,152</td>
</tr>
<tr class="even">
<td>W22TIL14</td>
<td>222</td>
<td>11,375</td>
</tr>
<tr class="odd">
<td>W22TIL25</td>
<td>310</td>
<td>14,857</td>
</tr>
<tr class="even">
<td>total / mean</td>
<td><strong>1,237</strong></td>
<td>13,700</td>
</tr>
</tbody>
</table>
<p>Mean 13,700 markers ≈ Chen 2019’s “average 13,733 high-quality SNPs per subpopulation.” Clean grid check: <code>1,237 × 51,482 = 63,683,234 = 17,159,588 present + 46,523,646 empty</code>.</p></li>
<li><p><strong>Genotype frequencies</strong> among present calls (dedup-invariant): <strong>0 = 76.65%, 1 (het) = 8.15%, 2 (teo hom) = 15.20%</strong> — matches the paper’s “15% homozygous teosinte, 8% heterozygous.”</p></li>
<li><p><strong>Reconciliation with phenotype (1,257 canonical RILs):</strong> inner-join on <code>(family, line)</code> = <strong>1,237</strong> — i.e.&nbsp;<strong>20 phenotyped RILs have no genotype in this EasiGP copy</strong> (scattered, not truncation; per family missing: TIL01 3, TIL03 3, TIL11 1, <strong>TIL14 13</strong>, TIL25 0). Genuine incompleteness of the convenience copy.</p></li>
<li><p><strong>Implication:</strong> use each family as a dense <code>nLines × family-markers</code> truth block (simulate reads per family at that family’s markers); no missingness to model on the truth side. Downstream densification to a common grid = <code>interpolate_genotype()</code> (nilHMM); see <code>agent/teonam-qtl-recovery-plan.md</code> §4.</p></li>
</ul>
</section>
<section id="teonam-marker-sets-the-thinningdensification-hierarchy" class="level2">
<h2 class="anchored" data-anchor-id="teonam-marker-sets-the-thinningdensification-hierarchy">TeoNAM marker sets (the thinning/densification hierarchy)</h2>
<p>All derive from the same cleaned genotypes; each row is a distinct marker count used downstream. Counts verified 2026-07-05.</p>
<p><strong>Naming system — <code>teonam_&lt;panel&gt;_&lt;assembly&gt;_&lt;role&gt;</code>.</strong> <code>panel</code> = <code>map</code> (all our data derives from the composite MAP panel); <code>assembly</code> = <code>v2</code> (marker-name coords) | <code>v5</code> (lifted); <code>role</code> = <code>family_imputed</code> (the base FSFHap within-family imputed calls) | <code>markers</code> (annotation) | <code>gwas</code> (GWAS base) | <code>jlm</code> (JLM base — thinned directly from <code>gwas</code>). (<code>gwas_nr</code> is a <strong>retired</strong> label, not a pipeline role: it does <strong>not</strong> feed JLM; kept only as the duplicate-cM record — see the table note below.) <strong>All map sets share the same base calls, which are FSFHap family-imputed</strong> (Chen’s map construction — complete <em>within family</em>; verified 0% partial-missing). So <code>family_imputed</code> is the base state, not a distinguishing step; the later suffixes describe downstream <em>selection</em>. The <code>family_imputed</code> label is deliberate: FSFHap imputes <strong>within each family</strong>, leaving cross-family gaps NA — distinct from the <code>interpolated</code> matrix, where our cross-family step-interpolation (Tian 2011 / Chen densifier) fills those gaps to supply the complete genotypes for <code>jlm</code> (and the interpolated GWAS matrix). Interpolation is a step, not a named panel.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>name</th>
<th>markers</th>
<th>assembly</th>
<th>role / provenance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>teonam_map_v2_family_imputed</code></td>
<td>51,482</td>
<td>v2</td>
<td><strong>FSFHap family-imputed</strong> recoded dosages (Chen map construction; complete <em>within family</em> — verified 0% partial-missing); EasiGP <code>TeoNAM_genotype_clean.csv</code>; coords in marker names</td>
</tr>
<tr class="even">
<td><code>teonam_map_v5_markers</code></td>
<td>51,065</td>
<td>v5</td>
<td>annotation (lift v2→v5 + consensus cM); <code>map_v5_coe2008.tsv</code> (<code>R/teonam_liftover.R</code>)</td>
</tr>
<tr class="odd">
<td><code>teonam_map_v5_gwas</code></td>
<td>51,004</td>
<td>v5</td>
<td><strong>GWAS base</strong> — per-marker, typed lines only; <code>stam_gwas_scan_family_imputed.csv</code></td>
</tr>
<tr class="even">
<td><code>teonam_map_v5_gwas_nr</code></td>
<td>47,750</td>
<td>v5</td>
<td>non-redundant (one marker per unique cM). <strong>Retained only as the record of the duplicate-cM markers (<code>agent/notes-redundant-markers.md</code>); NOT in any active path.</strong></td>
</tr>
<tr class="odd">
<td><code>teonam_map_v5_jlm</code></td>
<td>6,049</td>
<td>v5</td>
<td><strong>JLM base</strong> — FastIndep (<strong>cM-distance</strong> <span class="citation" data-cites="0.1">@0.1</span>) directly on <code>_gwas</code> (51,004); genotypes step-interpolated; <code>data/teonam/tassel/geno.hmp.txt</code> (<code>scripts/teonam_jlm_build.R</code>)</td>
</tr>
<tr class="even">
<td><code>teonam_gwas118k_v2_hapmap</code></td>
<td>118,838</td>
<td>v2 name / v4 pos</td>
<td><strong>authentic Chen 2019 GWAS panel</strong> (the real Fig 4C set) — TASSEL HapMap, single-char IUPAC, 1,257 RILs; from Qiuyue Chen’s Drive: <code>data/teonam/9250682/W22TILXX_Chr1-10.impute_filter_MR0.2_MAF0.05.hmp.txt</code></td>
</tr>
<tr class="odd">
<td><code>teonam_gwas118k_v5_markers</code></td>
<td>118,514</td>
<td>v5</td>
<td>v2→v5 liftover roster (chr from marker NAME, not the v4 <code>chrom</code> col); <code>markers_v5_gwas118k.tsv</code> (<code>scripts/teonam_lift_gwas118k.R</code>). 32,120/32,120 markers shared with <code>teonam_map_v5_markers</code> lift identically.</td>
</tr>
<tr class="even">
<td><code>teonam_gwas118k_v5_dosage</code></td>
<td>118,838</td>
<td>v5</td>
<td>additive dosage matrix [markers×1,257 lines], 2.72% NA; dosage = A2-allele count (TASSEL polarization, arbitrary vs W22/teo — fine for the flip-invariant STAM F-test); <code>teonam_gwas118k_dosage.rds</code> (<code>scripts/teonam_gwas118k_dosage.R</code>)</td>
</tr>
<tr class="odd">
<td><code>teonam_gwas118k_v5_scan</code></td>
<td>118,514</td>
<td>v5</td>
<td><strong>STAM GWAS scan</strong> on the 118K panel — <code>STAM ~ Family + marker</code>, 1-df F (same model as <code>stam_gwas_scan_family_imputed.csv</code>); <code>stam_gwas_scan_118k.csv</code> (<code>scripts/teonam_stam_gwas118k.R</code>)</td>
</tr>
<tr class="even">
<td><code>teonam_gwas118k_v5_dosage_polar</code></td>
<td>118,838</td>
<td>v5</td>
<td><strong>the coverage-sweep TRUTH</strong> — dosage polarized to W22↔︎teo (0=W22, 2=teo; 0 flips, 99.6% concordant with 51K), from the distributed imputed-nucleotide genotypes. These are the <em>real</em> per-SNP genotypes (ancestry is choppy, ~889 flips/chr — real per-SNP imputation het). The sweep Poisson-samples reads from these; the <strong>caller’s ancestry inference + back-projection does the smoothing</strong> (not a pre-smoothed input), which is why the truth stays the authentic per-SNP panel. <code>teonam_gwas118k_dosage_polar.rds</code> (<code>scripts/teonam_gwas118k_polarize.R</code>)</td>
</tr>
<tr class="odd">
<td><code>teonam_gwas118k_v5_dosage_fsfhap</code></td>
<td>118,514</td>
<td>v5</td>
<td>the <strong>ancestry-imputed panel</strong> (Fig-4C panel C + the source of <code>stam_gwas_scan_118k_complete_baseline.csv</code>) — the 118K block-smoothed with TASSEL5 <strong>FSFHap</strong> as Chen (bc, Phet=0.03125, Fillgaps, per family), parental (A/C) output → clean mosaic (~9 breakpoints/chr) step-interpolated to the union. <code>teonam_gwas118k_dosage_fsfhap.rds</code> (<code>teonam_gwas118k_fsfhap.R</code> + <code>teonam_gwas118k_truth_assemble.R</code>). <strong>NOT the sweep truth</strong> (superseded — the sweep uses the authentic per-SNP <code>_dosage_polar</code>; the ancestry smoothing belongs in the caller, not the truth).</td>
</tr>
<tr class="even">
<td><code>teonam_gwas118k_v5_cm</code></td>
<td>118,514</td>
<td>v5</td>
<td>native-cM grid (31,411 est.map-placed + 87,103 Marey-spline); <code>markers_v5_gwas118k_cm.tsv</code> (<code>scripts/teonam_gwas118k_cm_grid.R</code>)</td>
</tr>
<tr class="odd">
<td><code>teonam_gwas118k_v5_thin01</code></td>
<td>8,969</td>
<td>v5</td>
<td><strong>0.1 cM ancestry-inference grid</strong> (the exact maximum distance-<em>d</em> independent set on the 1-D cM axis via O(n) greedy — Jena et al.&nbsp;2018, <code>data/main.pdf</code>; no O(n²) matrix). The sweep HMMs infer segments on this grid, then back-project to the full 118K. <code>markers_v5_gwas118k_cm_thin01.tsv</code> (<code>scripts/teonam_gwas118k_thin01.R</code>)</td>
</tr>
<tr class="even">
<td><code>teonam_gwas118k_v5_&lt;caller&gt;_sweep</code></td>
<td>118,514</td>
<td>v5</td>
<td><strong>coverage-degradation sweeps</strong> — Poisson reads from the authentic per-SNP truth (<code>_dosage_polar</code>), ancestry inferred on the <strong>0.1 cM thin grid</strong> (<code>_thin01</code>), segments <strong>back-projected onto the full 118K</strong> for the STAM <code>~Family+marker</code> scan, at λ∈{0.1,0.2,0.5,1,5,10,20,∞}. <strong>λ=∞ is each caller at perfect coverage</strong> (deterministic decisive counts) — its own ceiling, in-pipeline (no shared baseline; per-caller). Four callers: <code>teonam_{rtiger,nnil,lbimpute,control}_sweep_118k.R</code> → <code>results/sim/teonam/stam_gwas_&lt;caller&gt;_118k_sweep.csv</code> (+ <code>_sweep_manhattan.png</code> via <code>teonam_sweep_manhattan_png.R</code>). One replicate/cell; peak heights not monotone in coverage (caller smoothing × real per-SNP noise).</td>
</tr>
</tbody>
</table>
<p>Notes: - <strong><code>teonam_gwas118k_*</code> is a NEW panel, a SIBLING of <code>map</code> — not derived from it.</strong> Both were filtered from the same raw 955,690 ZeaGBSv2.7 SNPs via different chains (map: MAF&lt;5% + 64-bp thin + FSFHap; GWAS: MAF&gt;1%, MR&lt;0.2, no thin, separate imputation). Name overlap with the 51K map panel is only 32,171 / 118,838 (86,667 GWAS-only, 19,373 map-only). This is the file whose absence made the earlier STAM Manhattan a non-faithful approximation — now resolved. - <strong>GWAS reproduction (2026-07-07):</strong> 118K scan gives max −log10P 19.8 (vs 14.3 for the 51K approx) and 8,392 genome-wide-significant hits concentrated on chr1 (4,901; tb1 region, v5 ~270–282 Mb), chr3 (3,428), chr7 (58) — matching Chen 2019’s STAM QTL architecture (STAM1.x/tb1, STAM3.x, STAM7.1). Decoding validated: all 32,158 shared markers correlate positively with the 51K coding (mean |r| 0.996). - <strong>Also in Chen’s Drive release</strong> (<code>9250682/</code>, per <code>Genotype_files_ReadMe.docx</code>), not yet all pulled: raw <code>W22TILXX_NoDepth.h5</code> (GBS in H5), <code>TeoNAM.filter0.1cM.snpInfor.txt</code> (4,578-SNP JLM subset), <code>TeoNAM_phenotype_07022018.txt</code> (4,578 SNPs + 22 traits for SAS JLM). - <strong><code>teonam_map_v5_jlm</code> thinning is a cM-distance thin, not an r² LD prune.</strong> <code>select_independent</code> (FastIndep, deterministic greedy) is fed the per-chr cM-distance matrix, so it enforces a hard 0.1 cM minimum spacing and does no LD decorrelation. The full pipeline is now reconstructed as a traceable script — <code>scripts/teonam_jlm_build.R</code> (FastIndep on the 51K pool + step-interpolated genotypes). <code>scripts/teonam_jlm_verify_source.R</code> reproduces the prior 47,750-pool hapmap <strong>0-mismatch</strong> (6,059 markers × 1,237 taxa), confirming the method. <code>analysis/marker-thinning.qmd</code> (written against the old 47,750 pool → 6,059) needs re-rendering to the 51K-pool set (6,049). - <strong>6,049 (<code>teonam_map_v5_jlm</code>) vs <code>chen2019_JLM</code> 4,578</strong> = map length (1781 vs 1540 cM, ×1.156) × 0.1-cM-bin saturation (×1.14) = ×1.32. Not a thinning-algorithm artifact. See <code>analysis/marker-thinning.qmd</code>. - <strong><code>teonam_map_v5_gwas_nr</code></strong> dedups markers sharing a cM (unique-cM grid, 47,750). It is <strong>no longer in any active path</strong> — JLM now thins directly from the 51K <code>_gwas</code> pool (cM-distance <span class="citation" data-cites="0.1">@0.1</span> subsumes the dedup: tied markers are 0 cM apart → one survivor per cluster). Retained only as the record of the duplicate-cM markers (~3,307 on the 51,004 base, centromeric low-recombination); see <code>agent/notes-redundant-markers.md</code>.</p>
<section id="what-chen-2019-has-vs-what-we-managed-reproduction-status-2026-07-05" class="level3">
<h3 class="anchored" data-anchor-id="what-chen-2019-has-vs-what-we-managed-reproduction-status-2026-07-05">What Chen 2019 has vs what we managed (reproduction status, 2026-07-05)</h3>
<p>We are reproducing Chen 2019 on the <strong>51,544-marker composite MAP panel</strong> (obtained via EasiGP; verified map-set-only). It’s a strong basis and the JLM anchors reproduce on it. Chen’s separate <strong>118,838-SNP GWAS set</strong> is not yet in hand (sibling of the map set — same raw 955,690 ZeaGBSv2.7 SNPs, different filter chain); we keep working on the 50K and will fold in the 118K once obtained (outreach: <code>agent/outreach_teonam_118k.md</code>).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>pipeline stage</th>
<th><code>chen2019_*</code> (published)</th>
<th><code>teonam_*</code> (this work)</th>
<th>status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>raw GBS calls</td>
<td>955,690 SNPs (ZeaGBSv2.7, AGPv2, HapMap)</td>
<td>not held (EasiGP ships post-filter 0/1/2 dosages)</td>
<td>to obtain</td>
</tr>
<tr class="even">
<td><strong>map panel</strong></td>
<td><code>chen2019_map</code> 51,544 — MAF&lt;5% + 64-bp thin → FSFHap → composite</td>
<td><code>teonam_map_v2_family_imputed</code> 51,482 / <code>teonam_map_v5_markers</code> 51,065</td>
<td>✓ have</td>
</tr>
<tr class="odd">
<td>genetic map</td>
<td>R/qtl <code>est.map</code>, 1540 cM, AGPv2 order</td>
<td>consensus Marey cM (Ed Coe composite), 1781 cM</td>
<td>different map</td>
</tr>
<tr class="even">
<td>coordinates</td>
<td>AGPv2 → AGPv4 (CrossMap)</td>
<td>AGPv2 → AGPv5 (liftover)</td>
<td>v5 vs v4</td>
</tr>
<tr class="odd">
<td><strong>JLM markers</strong></td>
<td><code>chen2019_JLM</code> 4,578 (0.1 cM thin of map set)</td>
<td><code>teonam_map_v5_jlm</code> 6,049 (FastIndep on cM-dist <span class="citation" data-cites="0.1">@0.1</span>, 51K pool)</td>
<td>✓ same op, denser/longer map</td>
</tr>
<tr class="even">
<td>JLM engine</td>
<td>SAS <code>PROC GLMSELECT</code>, marker nested-in-family, permutation threshold</td>
<td>TASSEL5 StepwiseOLS, nested-in-family, default threshold</td>
<td>perm threshold TODO</td>
</tr>
<tr class="odd">
<td>JLM result</td>
<td>STAM 5 QTL, DTA 19 QTL</td>
<td>recovers STAM QTL (more enter w/o perm cutoff)</td>
<td>reproducing</td>
</tr>
<tr class="even">
<td><strong>GWAS markers</strong></td>
<td><code>chen2019_GWAS</code> 118,838 (MAF&gt;0.01, unthinned → FSFHap)</td>
<td><code>teonam_map_v5_gwas</code> 51,004 (full set; also the JLM thinning pool)</td>
<td>118K to obtain</td>
</tr>
<tr class="odd">
<td>GWAS model</td>
<td>MLM: Q (5 PCs) + K (IBS)</td>
<td>OLS: Family + marker, 1-df F</td>
<td>MLM upgrade TODO</td>
</tr>
<tr class="even">
<td>GWAS threshold</td>
<td>P &lt; 1e-5 (LOD 5)</td>
<td>LOD 5</td>
<td>✓</td>
</tr>
</tbody>
</table>
<p>Consequences to keep closing (not blockers): the GWAS Manhattan on <code>teonam_map_v5_gwas</code> is sparser than <code>chen2019_GWAS</code> (some gaps, esp.&nbsp;low-recombination regions) and runs hotter (fixed OLS vs Q+K MLM → peak inflation; λ_GC analysis pending). JLM QTL recovery is the primary empirical-truth anchor and is unaffected by the GWAS-set gap.</p>
</section>
</section>
<section id="still-to-freeze-plan-b5-blocks-b2.3-b2.4" class="level2">
<h2 class="anchored" data-anchor-id="still-to-freeze-plan-b5-blocks-b2.3-b2.4">Still to freeze (plan B5 — blocks B2.3 / B2.4)</h2>
<ul class="task-list">
<li><label><input type="checkbox"><strong>~400 paired BrB + skim cohort manifest</strong> — IDs, donor species, per-source depth. Trace from <code>sample_metatada.csv</code> / <code>bzea-sample-donor-metadata</code> + the BRB and skim sample maps. Blocks <code>source-method-comparison.qmd</code>.</label></li>
<li><label><input type="checkbox">Which MolBreeding target-seq samples for the calibration cross-check.</label></li>
</ul>
<p>The B1 anthocyanin positive control (formerly the deferred <code>b1-mapping-benchmark.qmd</code>, now removed) was realized instead by the stem-pigment GWAS <code>analysis/zeal-qtl-recovery-stpi-mlm-snp50k-fdr.qmd</code> — no dedicated B1 phenotype table / NIL panel is required.</p>
</section>
<section id="missing-data-summaries-datamissing_data-gitignored" class="level2">
<h2 class="anchored" data-anchor-id="missing-data-summaries-datamissing_data-gitignored">§1 missing-data summaries (<code>data/missing_data/</code>, gitignored)</h2>
<p>Inputs for the §1 foundations notebooks <code>analysis/missing-data-floor-model.qmd</code> (part 2) and <code>analysis/missing-data-model-comparison.qmd</code> (part 3). Each is a tiny per-sample table of coverage (<code>lambda</code>) and observed missingness (<code>missing_obs</code>):</p>
<ul>
<li><code>wgs_per_sample.tsv</code> (1437 samples) — from <code>picard CollectWgsMetrics</code></li>
<li><code>wideseq_per_sample.tsv</code> (1434 samples) — 27 M teosinte-variant binned counts</li>
<li><code>snp50k_per_sample.tsv</code> (1439 samples) — 50 K panel per-site allelic counts</li>
</ul>
<p><strong>Source tables (native HPC paths, <code>/rsstu</code> — the mount <code>/Volumes/rsstu/...</code> is the same data but unstable):</strong></p>
<ul>
<li><code>/rsstu/users/r/rrellan/BZea/bzeaseq/WGSmetrics_summary.tsv</code> (296 KB)</li>
<li><code>/rsstu/users/r/rrellan/BZea/bzeaseq/ancestry/all_samples_bin_genotypes.tsv</code> (309 MB)</li>
<li><code>/rsstu/users/r/rrellan/BZea/bzeaseq/50K/allelic_counts50K.tsv</code> (2.4 GB)</li>
</ul>
<p><strong>How they were built (NCSU Hazel, LSF).</strong> The heavy reduction (esp.&nbsp;the 2.4 GB 50K read) runs on a compute node; only tiny summaries are pulled back. Scheduler is LSF.</p>
<ol type="1">
<li><p>Code (tracked): <code>scripts/make_missing_data_summaries.R</code> (reduces each source to a per-sample summary with <code>data.table::fread</code>, reading only the needed columns) and its submit wrapper <code>scripts/make_missing_data_summaries.lsf</code>.</p></li>
<li><p>R environment: the full <code>bzeaseq.yml</code> conda spec is no longer dependency-solvable, so a <strong>minimal</strong> env (<code>r-base</code> + <code>r-data.table</code>) is built on the <strong>login node</strong> (compute nodes have no internet) in fast scratch (ephemeral, ~1 month) by <code>scripts/build_missing_data_env.sh</code>:</p>
<pre><code>bash scripts/build_missing_data_env.sh   # -&gt; $RDT_ENV (default /share/&lt;grp&gt;/&lt;user&gt;/conda/env/rdt)</code></pre></li>
<li><p>Submit the reduction (native <code>/rsstu</code> reads, priority queue <code>sara</code>):</p>
<pre><code>cd /share/maize/frodrig4/zealhmm_jobs/missing_data
# (make_missing_data_summaries.{R,lsf} staged here)
bsub &lt; make_missing_data_summaries.lsf     # -&gt; out/{wgs,wideseq,snp50k}_per_sample.tsv</code></pre>
<p>The <code>.lsf</code> activates the <code>rdt</code> env, sets <code>BZEASEQ_DIR=/rsstu/users/r/rrellan/BZea/bzeaseq</code> and <code>OUT_DIR=$PWD/out</code>, and runs the R script (~20 s wall, incl.&nbsp;the 2.4 GB read).</p></li>
<li><p>Copy the three summaries back into <code>data/missing_data/</code> here. They are gitignored (local only); the notebooks read them and the executed render is shipped via the committed <code>docs/</code> HTML (Pages does not re-execute).</p></li>
</ol>
<p>To reproduce anywhere with the mount instead of the HPC, run the same R script with <code>BZEASEQ_DIR=/Volumes/rsstu/users/r/rrellan/BZea/bzeaseq</code>.</p>
</section>
<section id="zeal-inv4m-tagging-snp-genotype-comparison-datazeal-gitignored" class="level2">
<h2 class="anchored" data-anchor-id="zeal-inv4m-tagging-snp-genotype-comparison-datazeal-gitignored">ZEAL Inv4m tagging-SNP genotype comparison (<code>data/zeal/</code>, gitignored)</h2>
<p>Inputs for <code>analysis/zeal-inv4m-rtiger-genotype.qmd</code> (genotype at PZE04175660223, chr4:181,637,780):</p>
<ul>
<li><code>rtiger_200K_calls_introfinder.rds</code> — <strong>200K (previous)</strong> RTIGER segment calls, one table per NIL (<code>V1</code> chr, <code>V2</code> start, <code>V3</code> end, <code>V4</code> state ∈ {<code>B73</code>, <code>Introgression</code>}). Staged from <code>results_list_new_name.rds</code> in Nirwan Tandukar’s app repo <code>github.com/nirwan1265/BZea_Introgression_Finder</code> (the calls behind the inversion paper’s <code>inv4m_introgression</code> label). Names carry a <code>.B</code> bulk suffix → strip to match pedigree. <strong>Provenance (Nirwan DM 2025-08-15; a lineage SEPARATE from this repo’s BzeaSeq/wideseq work, and not reproducible here):</strong> Nirwan ran GATK HaplotypeCaller → joint genotyping on the BZea BAMs (<code>/rsstu/.../DOE_CAREER/BZea/joint_genotype/all_samps/9_final_samples/more_filtered/BZea.vcf.gz</code>, raw, ~98% missing) → MAF ≥ 0.05 + quality filter + rename → <strong>Beagle imputation by Asher (P. Balint-Kurti’s lab)</strong> → <code>BZea_MAF_0.05_qfiltered_newnames_imputed.vcf.gz</code> (196,120 SNPs) → RTIGER. It is <strong>excluded from the release</strong> (legacy, Beagle-imputed, no pipeline on hand; regenerate with recalibrated RTIGER on the SNP50K side if ever needed).</li>
<li><code>rtiger_50K_calls.csv</code> — <strong>50K (current)</strong> RTIGER 3-state segments (see <code>zeal_rtiger_mosaic.R</code>).</li>
<li><code>CLY25_ZEAL.csv</code>, <code>Bzea_metadata.csv</code> — spatially-corrected NC2025 phenotypes + donor metadata, staged from the inv4m Drive repo (<code>scripts/inversion_paper</code>).</li>
</ul>
<p>Both call sets are RTIGER; they differ only in the reference variant set. See memory <code>bzea-genotype-call-sets</code>.</p>
</section>
<section id="migration-from-zealtiger-plan-b3" class="level2">
<h2 class="anchored" data-anchor-id="migration-from-zealtiger-plan-b3">Migration from zealtiger (plan B3)</h2>
<p>The sanity-paint sweep inputs currently read from the zealtiger working repo (<code>results/sim_calibration/coverage_sweep_members.csv</code>, <code>data/rtiger_50K/</code>, <code>results/sim_calibration/brbseq_ks_wideseq/counts/</code>). Only the <strong>validated, paper-bound</strong> subsets migrate onto the mount / local <code>data/</code>; the <code>agent/</code> scratch tree is not copied.</p>
</section>
<section id="shareable-release-bundle-release-gitignored-cyverse" class="level2">
<h2 class="anchored" data-anchor-id="shareable-release-bundle-release-gitignored-cyverse">Shareable release bundle (<code>release/</code>, gitignored → CyVerse)</h2>
<p><code>scripts/zeal_export_release.R</code> assembles the citable BZea genotype release into <code>release/bzea_genotypes/</code> (bulk, gitignored; destined for the CyVerse Data Store with a DOI — Phase E of <code>SHAREABLE_DATASET_PLAN.md</code>). Fully reproducible from the tracked script + <code>scripts/release_README.md</code> template; ~156 MB, 30 files.</p>
<p>All five objects share <strong>one common callable panel</strong> (intersection of every object’s callable lines ≈ 1,395; the 8 near-empty libraries RTIGER’s per-chromosome QC can’t call are dropped) and ship in three encodings: PLINK <code>.bed/.bim/.fam</code> (canonical binary 012), tidy <code>_012.tsv.gz</code>, and the native <code>.rds</code>. Four are <strong>ancestry mosaics</strong> (<code>rtiger/nnil/binhmm/lbimpute</code>); the fifth, <strong><code>hwe_post_gt</code></strong>, is the <strong>genotype</strong> — the real <code>bcftools mpileup | call -mv</code> (HWE-prior MAP) calls from <code>bzea_50K_cohort.vcf.gz</code>, extracted for the panel (values = the bcftools calls, not a reconstruction). <strong>No single-sample GL genotypes are shared.</strong> Shared <code>markers/snp50k_markers.tsv</code> + <code>lines/snp50k_lines.tsv</code>; <code>MANIFEST.tsv</code> carries sha256 per file. The legacy <strong>200K</strong> RTIGER introgression set is <strong>not</strong> in the release (regenerate with recalibrated RTIGER if ever needed).</p>
<p>The cohort VCF is staged from <code>/Volumes/rsstu/.../bzeaseq/50K/results/joint/bzea_50K_cohort.vcf.gz</code> into <code>data/zeal/</code> (gitignored) and consumed by <code>scripts/zeal_hwe_post_gt.R</code>. The README states the wall (see <code>TERMINOLOGY.md</code>): a <code>_mosaic</code> PLINK/012 file encodes <strong>ancestry</strong> dosage on the SNP’s ref/alt alleles for tooling compatibility — it is not a genotype and does not report the true allele at invariant sites; only <code>hwe_post</code> does.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data provenance</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="in">`data/`</span>, <span class="in">`results/`</span>, and <span class="in">`sim/`</span> are **gitignored** (bulk inputs / generated</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>outputs — not tracked). Large inputs live on the mount and are referenced here;</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>resolve the mount roots with <span class="in">`R/staging.R::bzea_mounts()`</span> (<span class="in">`pick()`</span> fallback).</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>This file is the tracked record of where everything comes from.</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">## Mount roots</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Alias <span class="pp">|</span> Resolved by <span class="in">`bzea_mounts()`</span> <span class="pp">|</span> Holds <span class="pp">|</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="pp">|-------|-----------------------------|-------|</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`CAS`</span> (cassini) <span class="pp">|</span> <span class="in">`/Volumes/rsstu/.../tlaloc/cassini`</span> → <span class="in">`/Volumes/tlaloc/cassini`</span> → <span class="in">`/Volumes/cassini`</span> <span class="pp">|</span> pangene counts, gene→pangene map, B73 gene coords (ATLAS) <span class="pp">|</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`MNT`</span> (ancestry) <span class="pp">|</span> <span class="in">`/Volumes/rsstu/.../BZea/bzeaseq/ancestry`</span> → <span class="in">`/Volumes/BZea/bzeaseq/ancestry`</span> <span class="pp">|</span> per-bin <span class="in">`ALT_FREQ`</span> <span class="in">`*_bin_genotypes.tsv`</span> (dense skim, binhmm) <span class="pp">|</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data sources (naming `&lt;Source&gt;-&lt;Caller&gt;`)</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Source <span class="pp">|</span> Modality <span class="pp">|</span> Marker set <span class="pp">|</span> Notes <span class="pp">|</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="pp">|--------|----------|------------|-------|</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Skim <span class="pp">|</span> low-cov WGS (~0.4×) <span class="pp">|</span> 50K panel (thinned) + dense ~27.6 M wideseq <span class="pp">|</span> TP teosinte–B73 wideseq filter; MAF ≥ 0.05 <span class="pp">|</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> BrB <span class="pp">|</span> 3′ RNA-seq (BRB-seq) <span class="pp">|</span> wideseq-thinned counts + cassini pangene <span class="pp">|</span> expression-driven depth; ASE <span class="pp">|</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Target-seq <span class="pp">|</span> MolBreeding 45K, high cov <span class="pp">|</span> 45K array <span class="pp">|</span> completeness / Holland-style cross-check only <span class="pp">|</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>The ~27.6 M wideseq set = Schnable et al. 2023 teosinte/*Tripsacum* VCF →</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>biallelic → MAF ≥ 0.05 (<span class="in">`wideseq_ref`</span>); GATK <span class="in">`CollectAllelicCounts`</span> tallies</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>skim/BRB reads at those positions. (memory <span class="in">`snp50k-cohort-provenance`</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="in">`gatk-table-readcount-standard`</span>.)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Staged subset: skim sweep (`data/`, gitignored, ~33 MB)</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="in">`stage_sanity_check_paint.R`</span> copies the 11-sample vary-skim cohort (B73 control + 10</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>NILs) into <span class="in">`data/`</span>, organized by **(source × input type)** and consumed by</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="in">`analysis/nilhmm_sanity_check_paint.qmd`</span>. Verified: the note reproduces the original</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>zealtiger output **row-for-row** (1709 segments, all 6 tracks identical).</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="in">data/</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="in">  ref/                                genome-level, dataset-independent</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="in">    gene_to_pangene.tsv               ATLAS: pangene &lt;-&gt; B73 gene map</span></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a><span class="in">    b73_gene_coords.tsv               ATLAS: B73 gene coordinates</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a><span class="in">  skimsweep/                          the vary-skim cohort</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a><span class="in">    coverage_sweep_members.csv        full sweep table (note filters to vary_skim)</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a><span class="in">    skim/counts_50k/&lt;skim&gt;.tsv        -&gt; Skim-nNIL, Skim-rtiger</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a><span class="in">    skim/bins/&lt;skim&gt;_bin_genotypes.tsv-&gt; Skim-binhmm  (PER-SAMPLE only, never the aggregate)</span></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a><span class="in">    brb/counts_wideseq/&lt;brb&gt;.tsv      -&gt; BrB-nNIL, BrB-rtiger</span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a><span class="in">    brb/pangene/&lt;species&gt;/&lt;brb&gt;.pangene_counts.tsv  -&gt; BrB-atlas</span></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Staged path <span class="pp">|</span> Source <span class="pp">|</span></span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a><span class="pp">|-------------|--------|</span></span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`skimsweep/coverage_sweep_members.csv`</span>, <span class="in">`skim/counts_50k/`</span>, <span class="in">`brb/counts_wideseq/`</span> <span class="pp">|</span> zealtiger repo <span class="pp">|</span></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`skim/bins/&lt;skim&gt;_bin_genotypes.tsv`</span> <span class="pp">|</span> rsstu <span class="in">`BZea/bzeaseq/ancestry/&lt;skim&gt;_bin_genotypes.tsv`</span> (per-sample) <span class="pp">|</span></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`brb/pangene/`</span>, <span class="in">`ref/`</span> <span class="pp">|</span> rsstu <span class="in">`tlaloc/cassini/`</span> (<span class="in">`results/&lt;species&gt;/pangene/`</span>, <span class="in">`data/pangene/`</span>, <span class="in">`data/meta/`</span>) <span class="pp">|</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>Re-stage with <span class="in">`Rscript stage_sanity_check_paint.R`</span> **run with the sandbox disabled** —</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>both shares live under the <span class="in">`rsstu`</span> automount, which the default sandbox cannot</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>see (it reports the files as missing).</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## TeoNAM genotypes (`data/teonam/`, gitignored, ~236 MB)</span></span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>Recoded TeoNAM SNP genotypes (Chen et al. 2019, *Genetics* 213:1065; <span class="in">`chen2019teonam`</span>).</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>The genotypes cited in the paper at CyVerse <span class="in">`/iplant/home/shared/panzea/genotypes/GBS/TeosinteNAM`</span></span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a>are **no longer reachable** — the whole <span class="in">`panzea`</span> collection returns "not found" for our</span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>account and for anonymous CyVerse access (panzea.org still routes there and requires a</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>CyVerse login, so it is likely permission-gated to a group we're not in, not necessarily</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a>deleted). Figshare (9820178 / 9250682) has phenotypes/supplement only; panzea.org's Cornell</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>archive has only the older BC2S3 population (Yang et al. 2019 PNAS, <span class="in">`yang2019genetic`</span>).</span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>**Source used instead:** the EasiGP repo (Tomura et al. 2025, bioRxiv <span class="in">`10.1101/2025.07.15.664852`</span>,</span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a><span class="in">`tomura2025ensemble`</span>) vendors a recoded copy.</span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span>-<span class="pp">|</span>-<span class="pp">|</span></span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Paper <span class="pp">|</span> Tomura et al. 2025, bioRxiv <span class="in">`10.1101/2025.07.15.664852`</span> (<span class="in">`tomura2025ensemble`</span>) <span class="pp">|</span></span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Repo <span class="pp">|</span> https://github.com/ShunichiroT/EasiGP <span class="pp">|</span></span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Commit <span class="pp">|</span> <span class="in">`259c242006bce415a8995be1833ef44399655718`</span> (2026-06-16) <span class="pp">|</span></span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Path in repo <span class="pp">|</span> <span class="in">`Data/TeoNAM/`</span> <span class="pp">|</span></span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`TeoNAM_genotype.zip`</span> sha256 <span class="pp">|</span> <span class="in">`3a8b5adcdff6ed162032347ecaabe25fed5384ea8ed387f0b22fe492b2c6f918`</span> <span class="pp">|</span></span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a>Staged files (copied verbatim; <span class="in">`TeoNAM_genotype.csv`</span> is the unzipped <span class="in">`TeoNAM_genotype.zip`</span>):</span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a><span class="in">data/teonam/</span></span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a><span class="in">  TeoNAM_genotype.csv        2,434 lines x ~51,483 markers; 0/1/2 coding</span></span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a><span class="in">                             (0 = W22 hom, 1 = het, 2 = teosinte hom — paper's coding)</span></span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a><span class="in">  TeoNAM_phenotype.csv       2,434 lines; traits DTA, ASI only (2 of the paper's 22)</span></span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a><span class="in">  markers_v2.csv            51,544 markers; chromosome,name,start,end</span></span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a><span class="in">                             names like S1_10045 = chr1 / AGPv2 position 10045 (start/end are 0)</span></span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a><span class="in">  chrom.csv                  per-family chromosome spans</span></span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a><span class="in">  gene_info.csv              flowering-gene markers (Dong 2012, Wisser 2019)</span></span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a><span class="in">  W22TIL{01,03,11,14,25}_genotype.csv / _phenotype.csv   the 5 teosinte-parent subpopulations</span></span>
<span id="cb5-91"><a href="#cb5-91" aria-hidden="true" tabindex="-1"></a><span class="in">  W22TIL01_subset_*          small subset used by EasiGP as a quick example</span></span>
<span id="cb5-92"><a href="#cb5-92" aria-hidden="true" tabindex="-1"></a><span class="in">  TeoNAM_genotype.zip        original artifact (kept for integrity)</span></span>
<span id="cb5-93"><a href="#cb5-93" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-94"><a href="#cb5-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-95"><a href="#cb5-95" aria-hidden="true" tabindex="-1"></a>**Caveats (verify before analysis):**</span>
<span id="cb5-96"><a href="#cb5-96" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Numeric **dosage matrix only** — no raw HapMap / ref-alt alleles. Fine for ancestry-HMM</span>
<span id="cb5-97"><a href="#cb5-97" aria-hidden="true" tabindex="-1"></a>  (0/1/2 *is* the W22↔teosinte ancestry dosage); insufficient if raw allele calls or an</span>
<span id="cb5-98"><a href="#cb5-98" aria-hidden="true" tabindex="-1"></a>  AGPv2 VCF are needed (positions survive only in the marker names).</span>
<span id="cb5-99"><a href="#cb5-99" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Line count 2,434 exceeds the paper's 1,257 RILs — resolved (2026-07-04):** the file</span>
<span id="cb5-100"><a href="#cb5-100" aria-hidden="true" tabindex="-1"></a>  is EasiGP's per-family files concatenated, and each family file already doubles every</span>
<span id="cb5-101"><a href="#cb5-101" aria-hidden="true" tabindex="-1"></a>  line. The two copies of a line differ **only in <span class="in">`2`</span> vs <span class="in">`2.0`</span> integer/decimal</span>
<span id="cb5-102"><a href="#cb5-102" aria-hidden="true" tabindex="-1"></a>  formatting** — numerically identical (0/1,197 disagree). Cleaned to <span class="in">`TeoNAM_genotype_clean.csv`</span></span>
<span id="cb5-103"><a href="#cb5-103" aria-hidden="true" tabindex="-1"></a>  (see characterization below): dedup → **1,237** unique lines, all cells decimal.</span>
<span id="cb5-104"><a href="#cb5-104" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>"Adjusted example data" per EasiGP's <span class="in">`Data/README`</span> — treat as a re-derived convenience</span>
<span id="cb5-105"><a href="#cb5-105" aria-hidden="true" tabindex="-1"></a>  copy, not the authoritative release. For the authoritative genotypes, request access to</span>
<span id="cb5-106"><a href="#cb5-106" aria-hidden="true" tabindex="-1"></a>  the CyVerse <span class="in">`panzea`</span> collection from the authors (Qiuyue Chen / John Doebley).</span>
<span id="cb5-107"><a href="#cb5-107" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Assembly = AGPv2, documented first-party by Qiuyue Chen (not by EasiGP).** The marker-name</span>
<span id="cb5-108"><a href="#cb5-108" aria-hidden="true" tabindex="-1"></a>  positions (<span class="in">`S[chr]_[pos]`</span>) are B73 AGPv2, confirmed by three sources:</span>
<span id="cb5-109"><a href="#cb5-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-110"><a href="#cb5-110" aria-hidden="true" tabindex="-1"></a><span class="ss">  1. </span>**Chen's own genotype-release README** (<span class="in">`data/teonam/9250682/Genotype_files_ReadMe.docx`</span>,</span>
<span id="cb5-111"><a href="#cb5-111" aria-hidden="true" tabindex="-1"></a>     shared directly by Qiuyue Chen from her Google Drive) — the authoritative, first-party</span>
<span id="cb5-112"><a href="#cb5-112" aria-hidden="true" tabindex="-1"></a>     statement:</span>
<span id="cb5-113"><a href="#cb5-113" aria-hidden="true" tabindex="-1"></a><span class="at">     &gt; "The genetic map was estimated separately for each subpopulation using est.map function</span></span>
<span id="cb5-114"><a href="#cb5-114" aria-hidden="true" tabindex="-1"></a><span class="at">     &gt; in R/qtl, and the physical position is represented in marker name with **B73 V2 position</span></span>
<span id="cb5-115"><a href="#cb5-115" aria-hidden="true" tabindex="-1"></a><span class="at">     &gt; (S</span><span class="co">[</span><span class="ot">chr</span><span class="co">]</span><span class="at">_</span><span class="co">[</span><span class="ot">pos</span><span class="co">]</span><span class="at">)**."</span></span>
<span id="cb5-116"><a href="#cb5-116" aria-hidden="true" tabindex="-1"></a><span class="ss">  2. </span>**Chen et al. 2019** (Genetics 213:1065):</span>
<span id="cb5-117"><a href="#cb5-117" aria-hidden="true" tabindex="-1"></a><span class="at">     &gt; "The genotypic data were uploaded with **AGPv2 position in the marker name**." (Data Availability)</span></span>
<span id="cb5-118"><a href="#cb5-118" aria-hidden="true" tabindex="-1"></a><span class="at">     &gt; "The **B73 reference genome v2** was used to determine marker order..." (Methods)</span></span>
<span id="cb5-119"><a href="#cb5-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-120"><a href="#cb5-120" aria-hidden="true" tabindex="-1"></a>     AGPv4 appears in Chen 2019 **only** for *reporting* QTL positions (CrossMap-lifted from</span>
<span id="cb5-121"><a href="#cb5-121" aria-hidden="true" tabindex="-1"></a>     AGPv2); the genotype marker-name coordinates are AGPv2.</span>
<span id="cb5-122"><a href="#cb5-122" aria-hidden="true" tabindex="-1"></a><span class="ss">  3. </span>**EasiGP is silent on assembly.** The EasiGP repo and paper (Tomura et al. 2025, *Plant</span>
<span id="cb5-123"><a href="#cb5-123" aria-hidden="true" tabindex="-1"></a>     Genome*, doi:10.1002/tpg2.70138) only cite "adjusted example data from the TeoNAM dataset</span>
<span id="cb5-124"><a href="#cb5-124" aria-hidden="true" tabindex="-1"></a>     (Chen et al., 2019)" and never mention a genome build — so the version documentation is</span>
<span id="cb5-125"><a href="#cb5-125" aria-hidden="true" tabindex="-1"></a>     entirely Chen's.</span>
<span id="cb5-126"><a href="#cb5-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-127"><a href="#cb5-127" aria-hidden="true" tabindex="-1"></a>  **Marker-name identity checks (2026-07-07)** tying EasiGP back to Chen's documented panel:</span>
<span id="cb5-128"><a href="#cb5-128" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Chen's <span class="in">`TeoNAM.composite.genetic.map.51544snp.txt`</span> (51,544 names) **== EasiGP <span class="in">`marker_info.csv`</span></span>
<span id="cb5-129"><a href="#cb5-129" aria-hidden="true" tabindex="-1"></a>    (51,544 names)**: identical name sets, 0 unique to either side.</span>
<span id="cb5-130"><a href="#cb5-130" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>EasiGP <span class="in">`marker_info.csv`</span> is byte-identical to our <span class="in">`markers_v2.csv`</span> (md5 <span class="in">`6b29c715…`</span>).</span>
<span id="cb5-131"><a href="#cb5-131" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Our analyzed genotype matrix <span class="in">`TeoNAM_genotype_clean.csv`</span> (51,482 columns) is a clean subset</span>
<span id="cb5-132"><a href="#cb5-132" aria-hidden="true" tabindex="-1"></a>    of Chen's names (0 unrecognized columns; 62 Chen markers absent = the known 51,544→51,482 drop).</span>
<span id="cb5-133"><a href="#cb5-133" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>Independent physical check: per-chromosome max marker position fills the AGPv2 length and</span>
<span id="cb5-134"><a href="#cb5-134" aria-hidden="true" tabindex="-1"></a>    falls ~6–7 Mb short of v4/v5 (e.g. chr1 max 301,252,447 &lt; AGPv2 301,354,135 « v4 307,041,717).</span>
<span id="cb5-135"><a href="#cb5-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-136"><a href="#cb5-136" aria-hidden="true" tabindex="-1"></a>  (EasiGP repo clone kept at <span class="in">`agent/EasiGP/`</span>. Chen's Drive release, incl. the README, composite</span>
<span id="cb5-137"><a href="#cb5-137" aria-hidden="true" tabindex="-1"></a>  map, phenotypes, and — per the README — the 118,838-SNP GWAS HapMap + raw <span class="in">`.h5`</span>, is under</span>
<span id="cb5-138"><a href="#cb5-138" aria-hidden="true" tabindex="-1"></a>  <span class="in">`data/teonam/9250682/`</span>.)</span>
<span id="cb5-139"><a href="#cb5-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-140"><a href="#cb5-140" aria-hidden="true" tabindex="-1"></a>**Genotype-matrix characterization (measured 2026-07-04, full-scan of the raw and</span>
<span id="cb5-141"><a href="#cb5-141" aria-hidden="true" tabindex="-1"></a>cleaned files).** Raw <span class="in">`TeoNAM_genotype.csv`</span>: 2,434 rows × 51,482 marker columns</span>
<span id="cb5-142"><a href="#cb5-142" aria-hidden="true" tabindex="-1"></a>(cols 4–51485; first 3 = <span class="in">`ID, population, factor`</span>), CRLF endings. Cleaned artifact</span>
<span id="cb5-143"><a href="#cb5-143" aria-hidden="true" tabindex="-1"></a><span class="in">`TeoNAM_genotype_clean.csv`</span>: **1,237 rows × 51,482 markers, all decimals, LF**</span>
<span id="cb5-144"><a href="#cb5-144" aria-hidden="true" tabindex="-1"></a>(dedup + <span class="in">`2`</span>→<span class="in">`2.0`</span> normalization; original preserved).</span>
<span id="cb5-145"><a href="#cb5-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-146"><a href="#cb5-146" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The 2,434→1,237 doubling is a formatting artifact, not replicates.** Each line</span>
<span id="cb5-147"><a href="#cb5-147" aria-hidden="true" tabindex="-1"></a>  appears twice (byte-identical ID); the two copies are numerically identical and</span>
<span id="cb5-148"><a href="#cb5-148" aria-hidden="true" tabindex="-1"></a>  differ only in integer vs decimal spelling (<span class="in">`2`</span> vs <span class="in">`2.0`</span>). Raw matrix had 328,590</span>
<span id="cb5-149"><a href="#cb5-149" aria-hidden="true" tabindex="-1"></a>  integer-formatted cells (0.26%) vs 33.4M decimal; the clean file has **0** integer</span>
<span id="cb5-150"><a href="#cb5-150" aria-hidden="true" tabindex="-1"></a>  cells. Dedup keeps one copy → 1,237 unique lines.</span>
<span id="cb5-151"><a href="#cb5-151" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Imputed / complete within family — proven, not inferred.** For every family,</span>
<span id="cb5-152"><a href="#cb5-152" aria-hidden="true" tabindex="-1"></a>  each marker column is present in either *all* of the family's lines or *none*</span>
<span id="cb5-153"><a href="#cb5-153" aria-hidden="true" tabindex="-1"></a>  (0 partially-present columns) → within-family missingness **0%**; hard <span class="in">`0/1/2`</span></span>
<span id="cb5-154"><a href="#cb5-154" aria-hidden="true" tabindex="-1"></a>  calls only. This is the paper's per-subpopulation FSFHap-imputed output — not raw</span>
<span id="cb5-155"><a href="#cb5-155" aria-hidden="true" tabindex="-1"></a>  GBS, and not the cross-imputed/thinned 4,578-marker JLM matrix.</span>
<span id="cb5-156"><a href="#cb5-156" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Block-sparse union (73% blank, 100% structural):** each line is blank at other</span>
<span id="cb5-157"><a href="#cb5-157" aria-hidden="true" tabindex="-1"></a>  families' markers. Per-family line/marker counts (cleaned, one row per line):</span>
<span id="cb5-158"><a href="#cb5-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-159"><a href="#cb5-159" aria-hidden="true" tabindex="-1"></a>  | Family | nLines (clean) | markers (present per line) |</span>
<span id="cb5-160"><a href="#cb5-160" aria-hidden="true" tabindex="-1"></a>  |---|---|---|</span>
<span id="cb5-161"><a href="#cb5-161" aria-hidden="true" tabindex="-1"></a>  | W22TIL01 | 220 | 13,042 |</span>
<span id="cb5-162"><a href="#cb5-162" aria-hidden="true" tabindex="-1"></a>  | W22TIL03 | 267 | 16,076 |</span>
<span id="cb5-163"><a href="#cb5-163" aria-hidden="true" tabindex="-1"></a>  | W22TIL11 | 218 | 13,152 |</span>
<span id="cb5-164"><a href="#cb5-164" aria-hidden="true" tabindex="-1"></a>  | W22TIL14 | 222 | 11,375 |</span>
<span id="cb5-165"><a href="#cb5-165" aria-hidden="true" tabindex="-1"></a>  | W22TIL25 | 310 | 14,857 |</span>
<span id="cb5-166"><a href="#cb5-166" aria-hidden="true" tabindex="-1"></a>  | total / mean | **1,237** | 13,700 |</span>
<span id="cb5-167"><a href="#cb5-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-168"><a href="#cb5-168" aria-hidden="true" tabindex="-1"></a>  Mean 13,700 markers ≈ Chen 2019's "average 13,733 high-quality SNPs per subpopulation."</span>
<span id="cb5-169"><a href="#cb5-169" aria-hidden="true" tabindex="-1"></a>  Clean grid check: <span class="in">`1,237 × 51,482 = 63,683,234 = 17,159,588 present + 46,523,646 empty`</span>.</span>
<span id="cb5-170"><a href="#cb5-170" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Genotype frequencies** among present calls (dedup-invariant): **0 = 76.65%,</span>
<span id="cb5-171"><a href="#cb5-171" aria-hidden="true" tabindex="-1"></a>  1 (het) = 8.15%, 2 (teo hom) = 15.20%** — matches the paper's "15% homozygous</span>
<span id="cb5-172"><a href="#cb5-172" aria-hidden="true" tabindex="-1"></a>  teosinte, 8% heterozygous."</span>
<span id="cb5-173"><a href="#cb5-173" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Reconciliation with phenotype (1,257 canonical RILs):** inner-join on</span>
<span id="cb5-174"><a href="#cb5-174" aria-hidden="true" tabindex="-1"></a>  <span class="in">`(family, line)`</span> = **1,237** — i.e. **20 phenotyped RILs have no genotype in this</span>
<span id="cb5-175"><a href="#cb5-175" aria-hidden="true" tabindex="-1"></a>  EasiGP copy** (scattered, not truncation; per family missing: TIL01 3, TIL03 3,</span>
<span id="cb5-176"><a href="#cb5-176" aria-hidden="true" tabindex="-1"></a>  TIL11 1, **TIL14 13**, TIL25 0). Genuine incompleteness of the convenience copy.</span>
<span id="cb5-177"><a href="#cb5-177" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Implication:** use each family as a dense <span class="in">`nLines × family-markers`</span> truth block</span>
<span id="cb5-178"><a href="#cb5-178" aria-hidden="true" tabindex="-1"></a>  (simulate reads per family at that family's markers); no missingness to model on</span>
<span id="cb5-179"><a href="#cb5-179" aria-hidden="true" tabindex="-1"></a>  the truth side. Downstream densification to a common grid = <span class="in">`interpolate_genotype()`</span></span>
<span id="cb5-180"><a href="#cb5-180" aria-hidden="true" tabindex="-1"></a>  (nilHMM); see <span class="in">`agent/teonam-qtl-recovery-plan.md`</span> §4.</span>
<span id="cb5-181"><a href="#cb5-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-182"><a href="#cb5-182" aria-hidden="true" tabindex="-1"></a><span class="fu">## TeoNAM marker sets (the thinning/densification hierarchy)</span></span>
<span id="cb5-183"><a href="#cb5-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-184"><a href="#cb5-184" aria-hidden="true" tabindex="-1"></a>All derive from the same cleaned genotypes; each row is a distinct marker count used</span>
<span id="cb5-185"><a href="#cb5-185" aria-hidden="true" tabindex="-1"></a>downstream. Counts verified 2026-07-05.</span>
<span id="cb5-186"><a href="#cb5-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-187"><a href="#cb5-187" aria-hidden="true" tabindex="-1"></a>**Naming system — `teonam_&lt;panel&gt;_&lt;assembly&gt;_&lt;role&gt;`.** <span class="in">`panel`</span> = <span class="in">`map`</span> (all our data</span>
<span id="cb5-188"><a href="#cb5-188" aria-hidden="true" tabindex="-1"></a>derives from the composite MAP panel); <span class="in">`assembly`</span> = <span class="in">`v2`</span> (marker-name coords) | <span class="in">`v5`</span></span>
<span id="cb5-189"><a href="#cb5-189" aria-hidden="true" tabindex="-1"></a>(lifted); <span class="in">`role`</span> = <span class="in">`family_imputed`</span> (the base FSFHap within-family imputed calls) |</span>
<span id="cb5-190"><a href="#cb5-190" aria-hidden="true" tabindex="-1"></a><span class="in">`markers`</span> (annotation) | <span class="in">`gwas`</span> (GWAS base) | <span class="in">`jlm`</span> (JLM base — thinned directly from <span class="in">`gwas`</span>).</span>
<span id="cb5-191"><a href="#cb5-191" aria-hidden="true" tabindex="-1"></a>(<span class="in">`gwas_nr`</span> is a **retired** label, not a pipeline role: it does **not** feed JLM; kept only</span>
<span id="cb5-192"><a href="#cb5-192" aria-hidden="true" tabindex="-1"></a>as the duplicate-cM record — see the table note below.)</span>
<span id="cb5-193"><a href="#cb5-193" aria-hidden="true" tabindex="-1"></a>**All map sets share the same base calls, which are FSFHap family-imputed** (Chen's map</span>
<span id="cb5-194"><a href="#cb5-194" aria-hidden="true" tabindex="-1"></a>construction — complete *within family*; verified 0% partial-missing). So <span class="in">`family_imputed`</span> is</span>
<span id="cb5-195"><a href="#cb5-195" aria-hidden="true" tabindex="-1"></a>the base state, not a distinguishing step; the later suffixes describe downstream *selection*.</span>
<span id="cb5-196"><a href="#cb5-196" aria-hidden="true" tabindex="-1"></a>The <span class="in">`family_imputed`</span> label is deliberate: FSFHap imputes **within each family**, leaving</span>
<span id="cb5-197"><a href="#cb5-197" aria-hidden="true" tabindex="-1"></a>cross-family gaps NA — distinct from the <span class="in">`interpolated`</span> matrix, where our cross-family</span>
<span id="cb5-198"><a href="#cb5-198" aria-hidden="true" tabindex="-1"></a>step-interpolation (Tian 2011 / Chen densifier) fills those gaps to supply the complete</span>
<span id="cb5-199"><a href="#cb5-199" aria-hidden="true" tabindex="-1"></a>genotypes for <span class="in">`jlm`</span> (and the interpolated GWAS matrix). Interpolation is a step, not a named panel.</span>
<span id="cb5-200"><a href="#cb5-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-201"><a href="#cb5-201" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> name <span class="pp">|</span> markers <span class="pp">|</span> assembly <span class="pp">|</span> role / provenance <span class="pp">|</span></span>
<span id="cb5-202"><a href="#cb5-202" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb5-203"><a href="#cb5-203" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_map_v2_family_imputed`</span> <span class="pp">|</span> 51,482 <span class="pp">|</span> v2 <span class="pp">|</span> **FSFHap family-imputed** recoded dosages (Chen map construction; complete *within family* — verified 0% partial-missing); EasiGP <span class="in">`TeoNAM_genotype_clean.csv`</span>; coords in marker names <span class="pp">|</span></span>
<span id="cb5-204"><a href="#cb5-204" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_map_v5_markers`</span> <span class="pp">|</span> 51,065 <span class="pp">|</span> v5 <span class="pp">|</span> annotation (lift v2→v5 + consensus cM); <span class="in">`map_v5_coe2008.tsv`</span> (<span class="in">`R/teonam_liftover.R`</span>) <span class="pp">|</span></span>
<span id="cb5-205"><a href="#cb5-205" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_map_v5_gwas`</span> <span class="pp">|</span> 51,004 <span class="pp">|</span> v5 <span class="pp">|</span> **GWAS base** — per-marker, typed lines only; <span class="in">`stam_gwas_scan_family_imputed.csv`</span> <span class="pp">|</span></span>
<span id="cb5-206"><a href="#cb5-206" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_map_v5_gwas_nr`</span> <span class="pp">|</span> 47,750 <span class="pp">|</span> v5 <span class="pp">|</span> non-redundant (one marker per unique cM). **Retained only as the record of the duplicate-cM markers (`agent/notes-redundant-markers.md`); NOT in any active path.** <span class="pp">|</span></span>
<span id="cb5-207"><a href="#cb5-207" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_map_v5_jlm`</span> <span class="pp">|</span> 6,049 <span class="pp">|</span> v5 <span class="pp">|</span> **JLM base** — FastIndep (**cM-distance** @0.1) directly on <span class="in">`_gwas`</span> (51,004); genotypes step-interpolated; <span class="in">`data/teonam/tassel/geno.hmp.txt`</span> (<span class="in">`scripts/teonam_jlm_build.R`</span>) <span class="pp">|</span></span>
<span id="cb5-208"><a href="#cb5-208" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_gwas118k_v2_hapmap`</span> <span class="pp">|</span> 118,838 <span class="pp">|</span> v2 name / v4 pos <span class="pp">|</span> **authentic Chen 2019 GWAS panel** (the real Fig 4C set) — TASSEL HapMap, single-char IUPAC, 1,257 RILs; from Qiuyue Chen's Drive: <span class="in">`data/teonam/9250682/W22TILXX_Chr1-10.impute_filter_MR0.2_MAF0.05.hmp.txt`</span> <span class="pp">|</span></span>
<span id="cb5-209"><a href="#cb5-209" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_gwas118k_v5_markers`</span> <span class="pp">|</span> 118,514 <span class="pp">|</span> v5 <span class="pp">|</span> v2→v5 liftover roster (chr from marker NAME, not the v4 <span class="in">`chrom`</span> col); <span class="in">`markers_v5_gwas118k.tsv`</span> (<span class="in">`scripts/teonam_lift_gwas118k.R`</span>). 32,120/32,120 markers shared with <span class="in">`teonam_map_v5_markers`</span> lift identically. <span class="pp">|</span></span>
<span id="cb5-210"><a href="#cb5-210" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_gwas118k_v5_dosage`</span> <span class="pp">|</span> 118,838 <span class="pp">|</span> v5 <span class="pp">|</span> additive dosage matrix <span class="co">[</span><span class="ot">markers×1,257 lines</span><span class="co">]</span>, 2.72% NA; dosage = A2-allele count (TASSEL polarization, arbitrary vs W22/teo — fine for the flip-invariant STAM F-test); <span class="in">`teonam_gwas118k_dosage.rds`</span> (<span class="in">`scripts/teonam_gwas118k_dosage.R`</span>) <span class="pp">|</span></span>
<span id="cb5-211"><a href="#cb5-211" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_gwas118k_v5_scan`</span> <span class="pp">|</span> 118,514 <span class="pp">|</span> v5 <span class="pp">|</span> **STAM GWAS scan** on the 118K panel — <span class="in">`STAM ~ Family + marker`</span>, 1-df F (same model as <span class="in">`stam_gwas_scan_family_imputed.csv`</span>); <span class="in">`stam_gwas_scan_118k.csv`</span> (<span class="in">`scripts/teonam_stam_gwas118k.R`</span>) <span class="pp">|</span></span>
<span id="cb5-212"><a href="#cb5-212" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_gwas118k_v5_dosage_polar`</span> <span class="pp">|</span> 118,838 <span class="pp">|</span> v5 <span class="pp">|</span> **the coverage-sweep TRUTH** — dosage polarized to W22↔teo (0=W22, 2=teo; 0 flips, 99.6% concordant with 51K), from the distributed imputed-nucleotide genotypes. These are the *real* per-SNP genotypes (ancestry is choppy, ~889 flips/chr — real per-SNP imputation het). The sweep Poisson-samples reads from these; the **caller's ancestry inference + back-projection does the smoothing** (not a pre-smoothed input), which is why the truth stays the authentic per-SNP panel. <span class="in">`teonam_gwas118k_dosage_polar.rds`</span> (<span class="in">`scripts/teonam_gwas118k_polarize.R`</span>) <span class="pp">|</span></span>
<span id="cb5-213"><a href="#cb5-213" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_gwas118k_v5_dosage_fsfhap`</span> <span class="pp">|</span> 118,514 <span class="pp">|</span> v5 <span class="pp">|</span> the **ancestry-imputed panel** (Fig-4C panel C + the source of `stam_gwas_scan_118k_complete_baseline.csv`) — the 118K block-smoothed with TASSEL5 **FSFHap** as Chen (bc, Phet=0.03125, Fillgaps, per family), parental (A/C) output → clean mosaic (~9 breakpoints/chr) step-interpolated to the union. `teonam_gwas118k_dosage_fsfhap.rds` (`teonam_gwas118k_fsfhap.R` + `teonam_gwas118k_truth_assemble.R`). **NOT the sweep truth** (superseded — the sweep uses the authentic per-SNP <span class="in">`_dosage_polar`</span>; the ancestry smoothing belongs in the caller, not the truth). <span class="pp">|</span></span>
<span id="cb5-214"><a href="#cb5-214" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_gwas118k_v5_cm`</span> <span class="pp">|</span> 118,514 <span class="pp">|</span> v5 <span class="pp">|</span> native-cM grid (31,411 est.map-placed + 87,103 Marey-spline); <span class="in">`markers_v5_gwas118k_cm.tsv`</span> (<span class="in">`scripts/teonam_gwas118k_cm_grid.R`</span>) <span class="pp">|</span></span>
<span id="cb5-215"><a href="#cb5-215" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_gwas118k_v5_thin01`</span> <span class="pp">|</span> 8,969 <span class="pp">|</span> v5 <span class="pp">|</span> **0.1 cM ancestry-inference grid** (the exact maximum distance-*d* independent set on the 1-D cM axis via O(n) greedy — Jena et al. 2018, <span class="in">`data/main.pdf`</span>; no O(n²) matrix). The sweep HMMs infer segments on this grid, then back-project to the full 118K. <span class="in">`markers_v5_gwas118k_cm_thin01.tsv`</span> (<span class="in">`scripts/teonam_gwas118k_thin01.R`</span>) <span class="pp">|</span></span>
<span id="cb5-216"><a href="#cb5-216" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`teonam_gwas118k_v5_&lt;caller&gt;_sweep`</span> <span class="pp">|</span> 118,514 <span class="pp">|</span> v5 <span class="pp">|</span> **coverage-degradation sweeps** — Poisson reads from the authentic per-SNP truth (`_dosage_polar`), ancestry inferred on the **0.1 cM thin grid** (`_thin01`), segments **back-projected onto the full 118K** for the STAM `~Family+marker` scan, at λ∈{0.1,0.2,0.5,1,5,10,20,∞}. **λ=∞ is each caller at perfect coverage** (deterministic decisive counts) — its own ceiling, in-pipeline (no shared baseline; per-caller). Four callers: <span class="in">`teonam_{rtiger,nnil,lbimpute,control}_sweep_118k.R`</span> → <span class="in">`results/sim/teonam/stam_gwas_&lt;caller&gt;_118k_sweep.csv`</span> (+ <span class="in">`_sweep_manhattan.png`</span> via <span class="in">`teonam_sweep_manhattan_png.R`</span>). One replicate/cell; peak heights not monotone in coverage (caller smoothing × real per-SNP noise). <span class="pp">|</span></span>
<span id="cb5-217"><a href="#cb5-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-218"><a href="#cb5-218" aria-hidden="true" tabindex="-1"></a>Notes:</span>
<span id="cb5-219"><a href="#cb5-219" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`teonam_gwas118k_*` is a NEW panel, a SIBLING of `map` — not derived from it.** Both were</span>
<span id="cb5-220"><a href="#cb5-220" aria-hidden="true" tabindex="-1"></a>  filtered from the same raw 955,690 ZeaGBSv2.7 SNPs via different chains (map: MAF&lt;5% + 64-bp thin</span>
<span id="cb5-221"><a href="#cb5-221" aria-hidden="true" tabindex="-1"></a><span class="ss">  + </span>FSFHap; GWAS: MAF&gt;1%, MR&lt;0.2, no thin, separate imputation). Name overlap with the 51K map panel</span>
<span id="cb5-222"><a href="#cb5-222" aria-hidden="true" tabindex="-1"></a>  is only 32,171 / 118,838 (86,667 GWAS-only, 19,373 map-only). This is the file whose absence</span>
<span id="cb5-223"><a href="#cb5-223" aria-hidden="true" tabindex="-1"></a>  made the earlier STAM Manhattan a non-faithful approximation — now resolved.</span>
<span id="cb5-224"><a href="#cb5-224" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**GWAS reproduction (2026-07-07):** 118K scan gives max −log10P 19.8 (vs 14.3 for the 51K approx)</span>
<span id="cb5-225"><a href="#cb5-225" aria-hidden="true" tabindex="-1"></a>  and 8,392 genome-wide-significant hits concentrated on chr1 (4,901; tb1 region, v5 ~270–282 Mb),</span>
<span id="cb5-226"><a href="#cb5-226" aria-hidden="true" tabindex="-1"></a>  chr3 (3,428), chr7 (58) — matching Chen 2019's STAM QTL architecture (STAM1.x/tb1, STAM3.x, STAM7.1).</span>
<span id="cb5-227"><a href="#cb5-227" aria-hidden="true" tabindex="-1"></a>  Decoding validated: all 32,158 shared markers correlate positively with the 51K coding (mean |r| 0.996).</span>
<span id="cb5-228"><a href="#cb5-228" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Also in Chen's Drive release** (<span class="in">`9250682/`</span>, per <span class="in">`Genotype_files_ReadMe.docx`</span>), not yet all pulled:</span>
<span id="cb5-229"><a href="#cb5-229" aria-hidden="true" tabindex="-1"></a>  raw <span class="in">`W22TILXX_NoDepth.h5`</span> (GBS in H5), <span class="in">`TeoNAM.filter0.1cM.snpInfor.txt`</span> (4,578-SNP JLM subset),</span>
<span id="cb5-230"><a href="#cb5-230" aria-hidden="true" tabindex="-1"></a>  <span class="in">`TeoNAM_phenotype_07022018.txt`</span> (4,578 SNPs + 22 traits for SAS JLM).</span>
<span id="cb5-231"><a href="#cb5-231" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`teonam_map_v5_jlm` thinning is a cM-distance thin, not an r² LD prune.**</span>
<span id="cb5-232"><a href="#cb5-232" aria-hidden="true" tabindex="-1"></a>  <span class="in">`select_independent`</span> (FastIndep, deterministic greedy) is fed the per-chr cM-distance matrix, so</span>
<span id="cb5-233"><a href="#cb5-233" aria-hidden="true" tabindex="-1"></a>  it enforces a hard 0.1 cM minimum spacing and does no LD decorrelation. The full pipeline is now</span>
<span id="cb5-234"><a href="#cb5-234" aria-hidden="true" tabindex="-1"></a>  reconstructed as a traceable script — <span class="in">`scripts/teonam_jlm_build.R`</span> (FastIndep on the 51K pool +</span>
<span id="cb5-235"><a href="#cb5-235" aria-hidden="true" tabindex="-1"></a>  step-interpolated genotypes). <span class="in">`scripts/teonam_jlm_verify_source.R`</span> reproduces the prior</span>
<span id="cb5-236"><a href="#cb5-236" aria-hidden="true" tabindex="-1"></a>  47,750-pool hapmap **0-mismatch** (6,059 markers × 1,237 taxa), confirming the method.</span>
<span id="cb5-237"><a href="#cb5-237" aria-hidden="true" tabindex="-1"></a>  <span class="in">`analysis/marker-thinning.qmd`</span> (written against the old 47,750 pool → 6,059) needs</span>
<span id="cb5-238"><a href="#cb5-238" aria-hidden="true" tabindex="-1"></a>  re-rendering to the 51K-pool set (6,049).</span>
<span id="cb5-239"><a href="#cb5-239" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**6,049 (`teonam_map_v5_jlm`) vs `chen2019_JLM` 4,578** = map length (1781 vs 1540 cM,</span>
<span id="cb5-240"><a href="#cb5-240" aria-hidden="true" tabindex="-1"></a>  ×1.156) × 0.1-cM-bin saturation (×1.14) = ×1.32. Not a thinning-algorithm artifact.</span>
<span id="cb5-241"><a href="#cb5-241" aria-hidden="true" tabindex="-1"></a>  See <span class="in">`analysis/marker-thinning.qmd`</span>.</span>
<span id="cb5-242"><a href="#cb5-242" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`teonam_map_v5_gwas_nr`** dedups markers sharing a cM (unique-cM grid, 47,750). It is</span>
<span id="cb5-243"><a href="#cb5-243" aria-hidden="true" tabindex="-1"></a>  **no longer in any active path** — JLM now thins directly from the 51K <span class="in">`_gwas`</span> pool</span>
<span id="cb5-244"><a href="#cb5-244" aria-hidden="true" tabindex="-1"></a>  (cM-distance @0.1 subsumes the dedup: tied markers are 0 cM apart → one survivor per cluster).</span>
<span id="cb5-245"><a href="#cb5-245" aria-hidden="true" tabindex="-1"></a>  Retained only as the record of the duplicate-cM markers (~3,307 on the 51,004 base, centromeric</span>
<span id="cb5-246"><a href="#cb5-246" aria-hidden="true" tabindex="-1"></a>  low-recombination); see <span class="in">`agent/notes-redundant-markers.md`</span>.</span>
<span id="cb5-247"><a href="#cb5-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-248"><a href="#cb5-248" aria-hidden="true" tabindex="-1"></a><span class="fu">### What Chen 2019 has vs what we managed (reproduction status, 2026-07-05)</span></span>
<span id="cb5-249"><a href="#cb5-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-250"><a href="#cb5-250" aria-hidden="true" tabindex="-1"></a>We are reproducing Chen 2019 on the **51,544-marker composite MAP panel** (obtained via EasiGP;</span>
<span id="cb5-251"><a href="#cb5-251" aria-hidden="true" tabindex="-1"></a>verified map-set-only). It's a strong basis and the JLM anchors reproduce on it. Chen's separate</span>
<span id="cb5-252"><a href="#cb5-252" aria-hidden="true" tabindex="-1"></a>**118,838-SNP GWAS set** is not yet in hand (sibling of the map set — same raw 955,690 ZeaGBSv2.7</span>
<span id="cb5-253"><a href="#cb5-253" aria-hidden="true" tabindex="-1"></a>SNPs, different filter chain); we keep working on the 50K and will fold in the 118K once obtained</span>
<span id="cb5-254"><a href="#cb5-254" aria-hidden="true" tabindex="-1"></a>(outreach: <span class="in">`agent/outreach_teonam_118k.md`</span>).</span>
<span id="cb5-255"><a href="#cb5-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-256"><a href="#cb5-256" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> pipeline stage <span class="pp">|</span> <span class="in">`chen2019_*`</span> (published) <span class="pp">|</span> <span class="in">`teonam_*`</span> (this work) <span class="pp">|</span> status <span class="pp">|</span></span>
<span id="cb5-257"><a href="#cb5-257" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb5-258"><a href="#cb5-258" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> raw GBS calls <span class="pp">|</span> 955,690 SNPs (ZeaGBSv2.7, AGPv2, HapMap) <span class="pp">|</span> not held (EasiGP ships post-filter 0/1/2 dosages) <span class="pp">|</span> to obtain <span class="pp">|</span></span>
<span id="cb5-259"><a href="#cb5-259" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **map panel** <span class="pp">|</span> <span class="in">`chen2019_map`</span> 51,544 — MAF&lt;5% + 64-bp thin → FSFHap → composite <span class="pp">|</span> <span class="in">`teonam_map_v2_family_imputed`</span> 51,482 / <span class="in">`teonam_map_v5_markers`</span> 51,065 <span class="pp">|</span> ✓ have <span class="pp">|</span></span>
<span id="cb5-260"><a href="#cb5-260" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> genetic map <span class="pp">|</span> R/qtl <span class="in">`est.map`</span>, 1540 cM, AGPv2 order <span class="pp">|</span> consensus Marey cM (Ed Coe composite), 1781 cM <span class="pp">|</span> different map <span class="pp">|</span></span>
<span id="cb5-261"><a href="#cb5-261" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> coordinates <span class="pp">|</span> AGPv2 → AGPv4 (CrossMap) <span class="pp">|</span> AGPv2 → AGPv5 (liftover) <span class="pp">|</span> v5 vs v4 <span class="pp">|</span></span>
<span id="cb5-262"><a href="#cb5-262" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **JLM markers** <span class="pp">|</span> <span class="in">`chen2019_JLM`</span> 4,578 (0.1 cM thin of map set) <span class="pp">|</span> <span class="in">`teonam_map_v5_jlm`</span> 6,049 (FastIndep on cM-dist @0.1, 51K pool) <span class="pp">|</span> ✓ same op, denser/longer map <span class="pp">|</span></span>
<span id="cb5-263"><a href="#cb5-263" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> JLM engine <span class="pp">|</span> SAS <span class="in">`PROC GLMSELECT`</span>, marker nested-in-family, permutation threshold <span class="pp">|</span> TASSEL5 StepwiseOLS, nested-in-family, default threshold <span class="pp">|</span> perm threshold TODO <span class="pp">|</span></span>
<span id="cb5-264"><a href="#cb5-264" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> JLM result <span class="pp">|</span> STAM 5 QTL, DTA 19 QTL <span class="pp">|</span> recovers STAM QTL (more enter w/o perm cutoff) <span class="pp">|</span> reproducing <span class="pp">|</span></span>
<span id="cb5-265"><a href="#cb5-265" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **GWAS markers** <span class="pp">|</span> <span class="in">`chen2019_GWAS`</span> 118,838 (MAF&gt;0.01, unthinned → FSFHap) <span class="pp">|</span> <span class="in">`teonam_map_v5_gwas`</span> 51,004 (full set; also the JLM thinning pool) <span class="pp">|</span> 118K to obtain <span class="pp">|</span></span>
<span id="cb5-266"><a href="#cb5-266" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> GWAS model <span class="pp">|</span> MLM: Q (5 PCs) + K (IBS) <span class="pp">|</span> OLS: Family + marker, 1-df F <span class="pp">|</span> MLM upgrade TODO <span class="pp">|</span></span>
<span id="cb5-267"><a href="#cb5-267" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> GWAS threshold <span class="pp">|</span> P &lt; 1e-5 (LOD 5) <span class="pp">|</span> LOD 5 <span class="pp">|</span> ✓ <span class="pp">|</span></span>
<span id="cb5-268"><a href="#cb5-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-269"><a href="#cb5-269" aria-hidden="true" tabindex="-1"></a>Consequences to keep closing (not blockers): the GWAS Manhattan on <span class="in">`teonam_map_v5_gwas`</span> is</span>
<span id="cb5-270"><a href="#cb5-270" aria-hidden="true" tabindex="-1"></a>sparser than <span class="in">`chen2019_GWAS`</span> (some gaps, esp. low-recombination regions) and runs hotter (fixed</span>
<span id="cb5-271"><a href="#cb5-271" aria-hidden="true" tabindex="-1"></a>OLS vs Q+K MLM → peak inflation; λ_GC analysis pending). JLM QTL recovery is the primary</span>
<span id="cb5-272"><a href="#cb5-272" aria-hidden="true" tabindex="-1"></a>empirical-truth anchor and is unaffected by the GWAS-set gap.</span>
<span id="cb5-273"><a href="#cb5-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-274"><a href="#cb5-274" aria-hidden="true" tabindex="-1"></a><span class="fu">## Still to freeze (plan B5 — blocks B2.3 / B2.4)</span></span>
<span id="cb5-275"><a href="#cb5-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-276"><a href="#cb5-276" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[ ]</span> **~400 paired BrB + skim cohort manifest** — IDs, donor species, per-source</span>
<span id="cb5-277"><a href="#cb5-277" aria-hidden="true" tabindex="-1"></a>      depth. Trace from <span class="in">`sample_metatada.csv`</span> / <span class="in">`bzea-sample-donor-metadata`</span> +</span>
<span id="cb5-278"><a href="#cb5-278" aria-hidden="true" tabindex="-1"></a>      the BRB and skim sample maps. Blocks <span class="in">`source-method-comparison.qmd`</span>.</span>
<span id="cb5-279"><a href="#cb5-279" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[ ]</span> Which MolBreeding target-seq samples for the calibration cross-check.</span>
<span id="cb5-280"><a href="#cb5-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-281"><a href="#cb5-281" aria-hidden="true" tabindex="-1"></a>The B1 anthocyanin positive control (formerly the deferred <span class="in">`b1-mapping-benchmark.qmd`</span>,</span>
<span id="cb5-282"><a href="#cb5-282" aria-hidden="true" tabindex="-1"></a>now removed) was realized instead by the stem-pigment GWAS</span>
<span id="cb5-283"><a href="#cb5-283" aria-hidden="true" tabindex="-1"></a><span class="in">`analysis/zeal-qtl-recovery-stpi-mlm-snp50k-fdr.qmd`</span> — no dedicated B1 phenotype</span>
<span id="cb5-284"><a href="#cb5-284" aria-hidden="true" tabindex="-1"></a>table / NIL panel is required.</span>
<span id="cb5-285"><a href="#cb5-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-286"><a href="#cb5-286" aria-hidden="true" tabindex="-1"></a><span class="fu">## §1 missing-data summaries (`data/missing_data/`, gitignored)</span></span>
<span id="cb5-287"><a href="#cb5-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-288"><a href="#cb5-288" aria-hidden="true" tabindex="-1"></a>Inputs for the §1 foundations notebooks <span class="in">`analysis/missing-data-floor-model.qmd`</span></span>
<span id="cb5-289"><a href="#cb5-289" aria-hidden="true" tabindex="-1"></a>(part 2) and <span class="in">`analysis/missing-data-model-comparison.qmd`</span> (part 3). Each is a tiny</span>
<span id="cb5-290"><a href="#cb5-290" aria-hidden="true" tabindex="-1"></a>per-sample table of coverage (<span class="in">`lambda`</span>) and observed missingness (<span class="in">`missing_obs`</span>):</span>
<span id="cb5-291"><a href="#cb5-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-292"><a href="#cb5-292" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`wgs_per_sample.tsv`</span>      (1437 samples) — from <span class="in">`picard CollectWgsMetrics`</span></span>
<span id="cb5-293"><a href="#cb5-293" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`wideseq_per_sample.tsv`</span>  (1434 samples) — 27 M teosinte-variant binned counts</span>
<span id="cb5-294"><a href="#cb5-294" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`snp50k_per_sample.tsv`</span>   (1439 samples) — 50 K panel per-site allelic counts</span>
<span id="cb5-295"><a href="#cb5-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-296"><a href="#cb5-296" aria-hidden="true" tabindex="-1"></a>**Source tables (native HPC paths, <span class="in">`/rsstu`</span> — the mount <span class="in">`/Volumes/rsstu/...`</span> is the</span>
<span id="cb5-297"><a href="#cb5-297" aria-hidden="true" tabindex="-1"></a>same data but unstable):**</span>
<span id="cb5-298"><a href="#cb5-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-299"><a href="#cb5-299" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`/rsstu/users/r/rrellan/BZea/bzeaseq/WGSmetrics_summary.tsv`</span> (296 KB)</span>
<span id="cb5-300"><a href="#cb5-300" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`/rsstu/users/r/rrellan/BZea/bzeaseq/ancestry/all_samples_bin_genotypes.tsv`</span> (309 MB)</span>
<span id="cb5-301"><a href="#cb5-301" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`/rsstu/users/r/rrellan/BZea/bzeaseq/50K/allelic_counts50K.tsv`</span> (2.4 GB)</span>
<span id="cb5-302"><a href="#cb5-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-303"><a href="#cb5-303" aria-hidden="true" tabindex="-1"></a>**How they were built (NCSU Hazel, LSF).** The heavy reduction (esp. the 2.4 GB 50K</span>
<span id="cb5-304"><a href="#cb5-304" aria-hidden="true" tabindex="-1"></a>read) runs on a compute node; only tiny summaries are pulled back. Scheduler is LSF.</span>
<span id="cb5-305"><a href="#cb5-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-306"><a href="#cb5-306" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Code (tracked): <span class="in">`scripts/make_missing_data_summaries.R`</span> (reduces each source to a</span>
<span id="cb5-307"><a href="#cb5-307" aria-hidden="true" tabindex="-1"></a>   per-sample summary with <span class="in">`data.table::fread`</span>, reading only the needed columns) and</span>
<span id="cb5-308"><a href="#cb5-308" aria-hidden="true" tabindex="-1"></a>   its submit wrapper <span class="in">`scripts/make_missing_data_summaries.lsf`</span>.</span>
<span id="cb5-309"><a href="#cb5-309" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>R environment: the full <span class="in">`bzeaseq.yml`</span> conda spec is no longer dependency-solvable,</span>
<span id="cb5-310"><a href="#cb5-310" aria-hidden="true" tabindex="-1"></a>   so a **minimal** env (`r-base` + `r-data.table`) is built on the **login node**</span>
<span id="cb5-311"><a href="#cb5-311" aria-hidden="true" tabindex="-1"></a>   (compute nodes have no internet) in fast scratch (ephemeral, ~1 month) by</span>
<span id="cb5-312"><a href="#cb5-312" aria-hidden="true" tabindex="-1"></a>   <span class="in">`scripts/build_missing_data_env.sh`</span>:</span>
<span id="cb5-313"><a href="#cb5-313" aria-hidden="true" tabindex="-1"></a>   <span class="in">```</span></span>
<span id="cb5-314"><a href="#cb5-314" aria-hidden="true" tabindex="-1"></a><span class="in">   bash scripts/build_missing_data_env.sh   # -&gt; $RDT_ENV (default /share/&lt;grp&gt;/&lt;user&gt;/conda/env/rdt)</span></span>
<span id="cb5-315"><a href="#cb5-315" aria-hidden="true" tabindex="-1"></a><span class="in">   ```</span></span>
<span id="cb5-316"><a href="#cb5-316" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Submit the reduction (native <span class="in">`/rsstu`</span> reads, priority queue <span class="in">`sara`</span>):</span>
<span id="cb5-317"><a href="#cb5-317" aria-hidden="true" tabindex="-1"></a>   <span class="in">```</span></span>
<span id="cb5-318"><a href="#cb5-318" aria-hidden="true" tabindex="-1"></a><span class="in">   cd /share/maize/frodrig4/zealhmm_jobs/missing_data</span></span>
<span id="cb5-319"><a href="#cb5-319" aria-hidden="true" tabindex="-1"></a><span class="in">   # (make_missing_data_summaries.{R,lsf} staged here)</span></span>
<span id="cb5-320"><a href="#cb5-320" aria-hidden="true" tabindex="-1"></a><span class="in">   bsub &lt; make_missing_data_summaries.lsf     # -&gt; out/{wgs,wideseq,snp50k}_per_sample.tsv</span></span>
<span id="cb5-321"><a href="#cb5-321" aria-hidden="true" tabindex="-1"></a><span class="in">   ```</span></span>
<span id="cb5-322"><a href="#cb5-322" aria-hidden="true" tabindex="-1"></a>   The <span class="in">`.lsf`</span> activates the <span class="in">`rdt`</span> env, sets <span class="in">`BZEASEQ_DIR=/rsstu/users/r/rrellan/BZea/bzeaseq`</span></span>
<span id="cb5-323"><a href="#cb5-323" aria-hidden="true" tabindex="-1"></a>   and <span class="in">`OUT_DIR=$PWD/out`</span>, and runs the R script (~20 s wall, incl. the 2.4 GB read).</span>
<span id="cb5-324"><a href="#cb5-324" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Copy the three summaries back into <span class="in">`data/missing_data/`</span> here. They are gitignored</span>
<span id="cb5-325"><a href="#cb5-325" aria-hidden="true" tabindex="-1"></a>   (local only); the notebooks read them and the executed render is shipped via the</span>
<span id="cb5-326"><a href="#cb5-326" aria-hidden="true" tabindex="-1"></a>   committed <span class="in">`docs/`</span> HTML (Pages does not re-execute).</span>
<span id="cb5-327"><a href="#cb5-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-328"><a href="#cb5-328" aria-hidden="true" tabindex="-1"></a>To reproduce anywhere with the mount instead of the HPC, run the same R script with</span>
<span id="cb5-329"><a href="#cb5-329" aria-hidden="true" tabindex="-1"></a><span class="in">`BZEASEQ_DIR=/Volumes/rsstu/users/r/rrellan/BZea/bzeaseq`</span>.</span>
<span id="cb5-330"><a href="#cb5-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-331"><a href="#cb5-331" aria-hidden="true" tabindex="-1"></a><span class="fu">## ZEAL Inv4m tagging-SNP genotype comparison (`data/zeal/`, gitignored)</span></span>
<span id="cb5-332"><a href="#cb5-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-333"><a href="#cb5-333" aria-hidden="true" tabindex="-1"></a>Inputs for <span class="in">`analysis/zeal-inv4m-rtiger-genotype.qmd`</span> (genotype at PZE04175660223, chr4:181,637,780):</span>
<span id="cb5-334"><a href="#cb5-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-335"><a href="#cb5-335" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`rtiger_200K_calls_introfinder.rds`</span> — **200K (previous)** RTIGER segment calls, one table per NIL</span>
<span id="cb5-336"><a href="#cb5-336" aria-hidden="true" tabindex="-1"></a>  (<span class="in">`V1`</span> chr, <span class="in">`V2`</span> start, <span class="in">`V3`</span> end, <span class="in">`V4`</span> state ∈ {<span class="in">`B73`</span>, <span class="in">`Introgression`</span>}). Staged from</span>
<span id="cb5-337"><a href="#cb5-337" aria-hidden="true" tabindex="-1"></a>  <span class="in">`results_list_new_name.rds`</span> in Nirwan Tandukar's app repo</span>
<span id="cb5-338"><a href="#cb5-338" aria-hidden="true" tabindex="-1"></a>  <span class="in">`github.com/nirwan1265/BZea_Introgression_Finder`</span> (the calls behind the inversion paper's</span>
<span id="cb5-339"><a href="#cb5-339" aria-hidden="true" tabindex="-1"></a>  <span class="in">`inv4m_introgression`</span> label). Names carry a <span class="in">`.B`</span> bulk suffix → strip to match pedigree.</span>
<span id="cb5-340"><a href="#cb5-340" aria-hidden="true" tabindex="-1"></a>  **Provenance (Nirwan DM 2025-08-15; a lineage SEPARATE from this repo's BzeaSeq/wideseq work,</span>
<span id="cb5-341"><a href="#cb5-341" aria-hidden="true" tabindex="-1"></a>  and not reproducible here):** Nirwan ran GATK HaplotypeCaller → joint genotyping on the BZea BAMs</span>
<span id="cb5-342"><a href="#cb5-342" aria-hidden="true" tabindex="-1"></a>  (<span class="in">`/rsstu/.../DOE_CAREER/BZea/joint_genotype/all_samps/9_final_samples/more_filtered/BZea.vcf.gz`</span>,</span>
<span id="cb5-343"><a href="#cb5-343" aria-hidden="true" tabindex="-1"></a>  raw, ~98% missing) → MAF ≥ 0.05 + quality filter + rename → **Beagle imputation by Asher (P.</span>
<span id="cb5-344"><a href="#cb5-344" aria-hidden="true" tabindex="-1"></a>  Balint-Kurti's lab)** → <span class="in">`BZea_MAF_0.05_qfiltered_newnames_imputed.vcf.gz`</span> (196,120 SNPs) → RTIGER.</span>
<span id="cb5-345"><a href="#cb5-345" aria-hidden="true" tabindex="-1"></a>  It is **excluded from the release** (legacy, Beagle-imputed, no pipeline on hand; regenerate with</span>
<span id="cb5-346"><a href="#cb5-346" aria-hidden="true" tabindex="-1"></a>  recalibrated RTIGER on the SNP50K side if ever needed).</span>
<span id="cb5-347"><a href="#cb5-347" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`rtiger_50K_calls.csv`</span> — **50K (current)** RTIGER 3-state segments (see <span class="in">`zeal_rtiger_mosaic.R`</span>).</span>
<span id="cb5-348"><a href="#cb5-348" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="in">`CLY25_ZEAL.csv`</span>, <span class="in">`Bzea_metadata.csv`</span> — spatially-corrected NC2025 phenotypes + donor metadata,</span>
<span id="cb5-349"><a href="#cb5-349" aria-hidden="true" tabindex="-1"></a>  staged from the inv4m Drive repo (<span class="in">`scripts/inversion_paper`</span>).</span>
<span id="cb5-350"><a href="#cb5-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-351"><a href="#cb5-351" aria-hidden="true" tabindex="-1"></a>Both call sets are RTIGER; they differ only in the reference variant set. See memory</span>
<span id="cb5-352"><a href="#cb5-352" aria-hidden="true" tabindex="-1"></a><span class="in">`bzea-genotype-call-sets`</span>.</span>
<span id="cb5-353"><a href="#cb5-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-354"><a href="#cb5-354" aria-hidden="true" tabindex="-1"></a><span class="fu">## Migration from zealtiger (plan B3)</span></span>
<span id="cb5-355"><a href="#cb5-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-356"><a href="#cb5-356" aria-hidden="true" tabindex="-1"></a>The sanity-paint sweep inputs currently read from the zealtiger working repo</span>
<span id="cb5-357"><a href="#cb5-357" aria-hidden="true" tabindex="-1"></a>(<span class="in">`results/sim_calibration/coverage_sweep_members.csv`</span>, <span class="in">`data/rtiger_50K/`</span>,</span>
<span id="cb5-358"><a href="#cb5-358" aria-hidden="true" tabindex="-1"></a><span class="in">`results/sim_calibration/brbseq_ks_wideseq/counts/`</span>). Only the **validated,</span>
<span id="cb5-359"><a href="#cb5-359" aria-hidden="true" tabindex="-1"></a>paper-bound** subsets migrate onto the mount / local <span class="in">`data/`</span>; the <span class="in">`agent/`</span></span>
<span id="cb5-360"><a href="#cb5-360" aria-hidden="true" tabindex="-1"></a>scratch tree is not copied.</span>
<span id="cb5-361"><a href="#cb5-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-362"><a href="#cb5-362" aria-hidden="true" tabindex="-1"></a><span class="fu">## Shareable release bundle (`release/`, gitignored → CyVerse)</span></span>
<span id="cb5-363"><a href="#cb5-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-364"><a href="#cb5-364" aria-hidden="true" tabindex="-1"></a><span class="in">`scripts/zeal_export_release.R`</span> assembles the citable BZea genotype release into</span>
<span id="cb5-365"><a href="#cb5-365" aria-hidden="true" tabindex="-1"></a><span class="in">`release/bzea_genotypes/`</span> (bulk, gitignored; destined for the CyVerse Data Store with a</span>
<span id="cb5-366"><a href="#cb5-366" aria-hidden="true" tabindex="-1"></a>DOI — Phase E of <span class="in">`SHAREABLE_DATASET_PLAN.md`</span>). Fully reproducible from the tracked script</span>
<span id="cb5-367"><a href="#cb5-367" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span><span class="in">`scripts/release_README.md`</span> template; ~156 MB, 30 files.</span>
<span id="cb5-368"><a href="#cb5-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-369"><a href="#cb5-369" aria-hidden="true" tabindex="-1"></a>All five objects share **one common callable panel** (intersection of every object's callable</span>
<span id="cb5-370"><a href="#cb5-370" aria-hidden="true" tabindex="-1"></a>lines ≈ 1,395; the 8 near-empty libraries RTIGER's per-chromosome QC can't call are dropped) and</span>
<span id="cb5-371"><a href="#cb5-371" aria-hidden="true" tabindex="-1"></a>ship in three encodings: PLINK <span class="in">`.bed/.bim/.fam`</span> (canonical binary 012), tidy <span class="in">`_012.tsv.gz`</span>, and</span>
<span id="cb5-372"><a href="#cb5-372" aria-hidden="true" tabindex="-1"></a>the native <span class="in">`.rds`</span>. Four are **ancestry mosaics** (<span class="in">`rtiger/nnil/binhmm/lbimpute`</span>); the fifth,</span>
<span id="cb5-373"><a href="#cb5-373" aria-hidden="true" tabindex="-1"></a>**`hwe_post_gt`**, is the **genotype** — the real <span class="in">`bcftools mpileup | call -mv`</span> (HWE-prior MAP)</span>
<span id="cb5-374"><a href="#cb5-374" aria-hidden="true" tabindex="-1"></a>calls from <span class="in">`bzea_50K_cohort.vcf.gz`</span>, extracted for the panel (values = the bcftools calls, not a</span>
<span id="cb5-375"><a href="#cb5-375" aria-hidden="true" tabindex="-1"></a>reconstruction). **No single-sample GL genotypes are shared.** Shared <span class="in">`markers/snp50k_markers.tsv`</span></span>
<span id="cb5-376"><a href="#cb5-376" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span><span class="in">`lines/snp50k_lines.tsv`</span>; <span class="in">`MANIFEST.tsv`</span> carries sha256 per file.</span>
<span id="cb5-377"><a href="#cb5-377" aria-hidden="true" tabindex="-1"></a>The legacy **200K** RTIGER introgression set is **not** in the release (regenerate with</span>
<span id="cb5-378"><a href="#cb5-378" aria-hidden="true" tabindex="-1"></a>recalibrated RTIGER if ever needed).</span>
<span id="cb5-379"><a href="#cb5-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-380"><a href="#cb5-380" aria-hidden="true" tabindex="-1"></a>The cohort VCF is staged from <span class="in">`/Volumes/rsstu/.../bzeaseq/50K/results/joint/bzea_50K_cohort.vcf.gz`</span></span>
<span id="cb5-381"><a href="#cb5-381" aria-hidden="true" tabindex="-1"></a>into <span class="in">`data/zeal/`</span> (gitignored) and consumed by <span class="in">`scripts/zeal_hwe_post_gt.R`</span>. The README states the</span>
<span id="cb5-382"><a href="#cb5-382" aria-hidden="true" tabindex="-1"></a>wall (see <span class="in">`TERMINOLOGY.md`</span>): a <span class="in">`_mosaic`</span> PLINK/012 file encodes **ancestry** dosage on the SNP's</span>
<span id="cb5-383"><a href="#cb5-383" aria-hidden="true" tabindex="-1"></a>ref/alt alleles for tooling compatibility — it is not a genotype and does not report the true</span>
<span id="cb5-384"><a href="#cb5-384" aria-hidden="true" tabindex="-1"></a>allele at invariant sites; only <span class="in">`hwe_post`</span> does.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>